/**
 * Bonus tools batch - Final push to 1000+ tools
 * Adds 200+ additional tools across various categories
 */

const bonusTools = [
    // ==================== MORE NOTE-TAKING & PKM ====================
    { id: "obsidian", category: "notes", name: "Obsidian", tagline: "Knowledge base", description: "Powerful knowledge base that works on local Markdown files.", website: "https://obsidian.md", license: "Proprietary", platforms: ["windows", "macos", "linux", "ios", "android"], tags: ["markdown", "knowledge-base", "linking"], alternatives_to: ["Notion", "Roam Research"], last_update: "2026-01-15", is_foss: false, maturity: "stable" },
    { id: "logseq", category: "notes", name: "Logseq", tagline: "Outliner knowledge base", description: "Privacy-first, open-source knowledge base that works on local files.", website: "https://logseq.com", license: "AGPL-3.0", platforms: ["windows", "macos", "linux", "ios", "android"], tags: ["outliner", "knowledge-base", "privacy"], alternatives_to: ["Roam Research", "Obsidian"], last_update: "2026-01-10", repo_url: "https://github.com/logseq/logseq", is_foss: true, stars: 32000, maturity: "stable" },
    { id: "anytype", category: "notes", name: "Anytype", tagline: "Local-first workspace", description: "Local-first, P2P knowledge management tool.", website: "https://anytype.io", license: "Custom", platforms: ["windows", "macos", "linux", "ios", "android"], tags: ["knowledge-base", "local-first", "p2p"], alternatives_to: ["Notion"], last_update: "2025-12-20", repo_url: "https://github.com/anyproto/anytype-ts", is_foss: true, stars: 4000, maturity: "growing" },
    { id: "appflowy", category: "notes", name: "AppFlowy", tagline: "Notion alternative", description: "Open-source alternative to Notion with privacy focus.", website: "https://appflowy.io", license: "AGPL-3.0", platforms: ["windows", "macos", "linux", "ios", "android"], tags: ["notion-alternative", "privacy", "workspace"], alternatives_to: ["Notion"], last_update: "2026-01-08", repo_url: "https://github.com/AppFlowy-IO/AppFlowy", is_foss: true, stars: 55000, maturity: "growing" },
    { id: "affine", category: "notes", name: "AFFiNE", tagline: "Knowledge base", description: "Next-gen knowledge base that brings planning, sorting and creating together.", website: "https://affine.pro", license: "MIT", platforms: ["windows", "macos", "linux", "web"], tags: ["knowledge-base", "whiteboard", "docs"], alternatives_to: ["Notion", "Miro"], last_update: "2026-01-12", repo_url: "https://github.com/toeverything/AFFiNE", is_foss: true, stars: 40000, maturity: "growing" },
    { id: "trilium", category: "notes", name: "Trilium Notes", tagline: "Hierarchical note-taking", description: "Hierarchical note-taking application with focus on building personal knowledge bases.", website: "https://github.com/zadam/trilium", license: "AGPL-3.0", platforms: ["windows", "macos", "linux", "self-hosted"], tags: ["notes", "hierarchical", "knowledge-base"], alternatives_to: ["Obsidian"], last_update: "2025-12-15", repo_url: "https://github.com/zadam/trilium", is_foss: true, stars: 27000, maturity: "stable" },
    { id: "joplin", category: "notes", name: "Joplin", tagline: "Note-taking app", description: "Open-source note-taking and to-do application with synchronization.", website: "https://joplinapp.org", license: "AGPL-3.0", platforms: ["windows", "macos", "linux", "ios", "android"], tags: ["notes", "sync", "markdown"], alternatives_to: ["Evernote"], last_update: "2025-12-20", repo_url: "https://github.com/laurent22/joplin", is_foss: true, stars: 46000, maturity: "stable" },
    { id: "standardnotes", category: "notes", name: "Standard Notes", tagline: "Encrypted notes", description: "Free, open-source, and end-to-end encrypted notes app.", website: "https://standardnotes.com", license: "AGPL-3.0", platforms: ["windows", "macos", "linux", "ios", "android", "web"], tags: ["notes", "encryption", "privacy"], alternatives_to: ["Evernote"], last_update: "2025-12-15", repo_url: "https://github.com/standardnotes/app", is_foss: true, stars: 5200, maturity: "stable" },
    { id: "notesnook", category: "notes", name: "Notesnook", tagline: "Private notes app", description: "Open-source and end-to-end encrypted note-taking alternative to Evernote.", website: "https://notesnook.com", license: "GPL-3.0", platforms: ["windows", "macos", "linux", "ios", "android", "web"], tags: ["notes", "encryption", "privacy"], alternatives_to: ["Evernote"], last_update: "2025-12-20", repo_url: "https://github.com/streetwriters/notesnook", is_foss: true, stars: 9500, maturity: "stable" },
    { id: "silverbullet", category: "notes", name: "SilverBullet", tagline: "Hackable notebook", description: "Note-taking application optimized for people with a hacker mindset.", website: "https://silverbullet.md", license: "MIT", platforms: ["web", "self-hosted"], tags: ["notes", "hackable", "markdown"], alternatives_to: ["Obsidian"], last_update: "2025-12-15", repo_url: "https://github.com/silverbulletmd/silverbullet", is_foss: true, stars: 3000, maturity: "growing" },

    // ==================== MORE PROJECT MANAGEMENT ====================
    { id: "plane", category: "project", name: "Plane", tagline: "Project management", description: "Open-source project planning tool as an alternative to Jira.", website: "https://plane.so", license: "AGPL-3.0", platforms: ["web", "self-hosted"], tags: ["project-management", "jira-alternative", "agile"], alternatives_to: ["Jira", "Linear"], last_update: "2026-01-10", repo_url: "https://github.com/makeplane/plane", is_foss: true, stars: 30000, maturity: "growing" },
    { id: "focalboard", category: "project", name: "Focalboard", tagline: "Project management", description: "Open-source, self-hosted alternative to Trello, Notion, and Asana.", website: "https://www.focalboard.com", license: "AGPL-3.0", platforms: ["windows", "macos", "linux", "self-hosted"], tags: ["kanban", "project-management", "self-hosted"], alternatives_to: ["Trello", "Notion"], last_update: "2025-12-15", repo_url: "https://github.com/mattermost/focalboard", is_foss: true, stars: 21000, maturity: "stable" },
    { id: "taiga", category: "project", name: "Taiga", tagline: "Agile project management", description: "Free and open-source project management platform for agile developers.", website: "https://taiga.io", license: "MPL-2.0", platforms: ["web", "self-hosted"], tags: ["agile", "scrum", "kanban"], alternatives_to: ["Jira"], last_update: "2025-12-20", repo_url: "https://github.com/taigaio/taiga-back", is_foss: true, stars: 3500, maturity: "stable" },
    { id: "openproject", category: "project", name: "OpenProject", tagline: "Project management", description: "Open-source project management software with Gantt charts and agile boards.", website: "https://www.openproject.org", license: "GPL-3.0", platforms: ["web", "self-hosted"], tags: ["project-management", "gantt", "agile"], alternatives_to: ["Microsoft Project", "Jira"], last_update: "2025-12-15", repo_url: "https://github.com/opf/openproject", is_foss: true, stars: 9000, maturity: "stable" },
    { id: "wekan", category: "project", name: "WeKan", tagline: "Kanban board", description: "Open-source kanban board with MIT license.", website: "https://wekan.github.io", license: "MIT", platforms: ["web", "self-hosted"], tags: ["kanban", "boards", "self-hosted"], alternatives_to: ["Trello"], last_update: "2025-12-20", repo_url: "https://github.com/wekan/wekan", is_foss: true, stars: 19500, maturity: "stable" },
    { id: "kanboard", category: "project", name: "Kanboard", tagline: "Kanban project management", description: "Free and open-source Kanban project management software.", website: "https://kanboard.org", license: "MIT", platforms: ["web", "self-hosted"], tags: ["kanban", "simple", "self-hosted"], alternatives_to: ["Trello"], last_update: "2025-11-20", repo_url: "https://github.com/kanboard/kanboard", is_foss: true, stars: 8500, maturity: "stable" },
    { id: "vikunja", category: "project", name: "Vikunja", tagline: "To-do app", description: "Open-source, self-hostable to-do app.", website: "https://vikunja.io", license: "AGPL-3.0", platforms: ["web", "self-hosted", "ios", "android"], tags: ["todo", "tasks", "self-hosted"], alternatives_to: ["Todoist"], last_update: "2025-12-15", repo_url: "https://kolaente.dev/vikunja/vikunja", is_foss: true, stars: 2500, maturity: "stable" },
    { id: "super-productivity", category: "project", name: "Super Productivity", tagline: "To-do list & time tracker", description: "To-do list and time tracker for programmers and designers.", website: "https://super-productivity.com", license: "MIT", platforms: ["windows", "macos", "linux", "ios", "android"], tags: ["todo", "time-tracking", "productivity"], alternatives_to: ["Todoist"], last_update: "2025-12-20", repo_url: "https://github.com/johannesjo/super-productivity", is_foss: true, stars: 11000, maturity: "stable" },

    // ==================== MORE PASSWORD MANAGERS ====================
    { id: "bitwarden", category: "password", name: "Bitwarden", tagline: "Password manager", description: "Open-source password management solution for individuals and organizations.", website: "https://bitwarden.com", license: "GPL-3.0", platforms: ["windows", "macos", "linux", "ios", "android", "web"], tags: ["passwords", "security", "sync"], alternatives_to: ["LastPass", "1Password"], last_update: "2026-01-10", repo_url: "https://github.com/bitwarden/clients", is_foss: true, stars: 9000, maturity: "stable" },
    { id: "keepassxc", category: "password", name: "KeePassXC", tagline: "Password manager", description: "Cross-platform community-driven port of KeePass.", website: "https://keepassxc.org", license: "GPL-3.0", platforms: ["windows", "macos", "linux"], tags: ["passwords", "offline", "security"], alternatives_to: ["1Password"], last_update: "2025-12-20", repo_url: "https://github.com/keepassxreboot/keepassxc", is_foss: true, stars: 21000, maturity: "stable" },
    { id: "passbolt", category: "password", name: "Passbolt", tagline: "Team password manager", description: "Open-source password manager for teams.", website: "https://www.passbolt.com", license: "AGPL-3.0", platforms: ["web", "self-hosted"], tags: ["passwords", "team", "enterprise"], alternatives_to: ["1Password Teams"], last_update: "2025-12-15", repo_url: "https://github.com/passbolt/passbolt_api", is_foss: true, stars: 4800, maturity: "stable" },
    { id: "padloc", category: "password", name: "Padloc", tagline: "Password manager", description: "Modern, open-source password manager for individuals and teams.", website: "https://padloc.app", license: "GPL-3.0", platforms: ["windows", "macos", "linux", "ios", "android", "web"], tags: ["passwords", "modern", "sync"], alternatives_to: ["1Password"], last_update: "2025-11-20", repo_url: "https://github.com/padloc/padloc", is_foss: true, stars: 2600, maturity: "stable" },

    // ==================== MORE PRIVACY TOOLS ====================
    { id: "simplelogin", category: "privacy", name: "SimpleLogin", tagline: "Email aliasing", description: "Open-source email aliasing solution to protect your email address.", website: "https://simplelogin.io", license: "MIT", platforms: ["web", "self-hosted"], tags: ["email", "privacy", "aliasing"], alternatives_to: ["AnonAddy"], last_update: "2025-12-20", repo_url: "https://github.com/simple-login/app", is_foss: true, stars: 5000, maturity: "stable" },
    { id: "anonaddy", category: "privacy", name: "AnonAddy", tagline: "Email forwarding", description: "Anonymous email forwarding service.", website: "https://anonaddy.com", license: "MIT", platforms: ["web", "self-hosted"], tags: ["email", "privacy", "forwarding"], alternatives_to: ["SimpleLogin"], last_update: "2025-12-15", repo_url: "https://github.com/anonaddy/anonaddy", is_foss: true, stars: 3200, maturity: "stable" },
    { id: "protonmail", category: "privacy", name: "Proton Mail", tagline: "Encrypted email", description: "End-to-end encrypted email service.", website: "https://proton.me/mail", license: "GPL-3.0", platforms: ["web", "ios", "android"], tags: ["email", "encryption", "privacy"], alternatives_to: ["Gmail"], last_update: "2026-01-10", repo_url: "https://github.com/ProtonMail/WebClients", is_foss: true, stars: 4500, maturity: "stable" },
    { id: "tutanota", category: "privacy", name: "Tuta", tagline: "Encrypted email", description: "End-to-end encrypted email service with calendar.", website: "https://tuta.com", license: "GPL-3.0", platforms: ["windows", "macos", "linux", "ios", "android", "web"], tags: ["email", "encryption", "calendar"], alternatives_to: ["Gmail"], last_update: "2025-12-20", repo_url: "https://github.com/tutao/tutanota", is_foss: true, stars: 6000, maturity: "stable" },
    { id: "signal", category: "privacy", name: "Signal", tagline: "Encrypted messaging", description: "Privacy-focused messaging app with end-to-end encryption.", website: "https://signal.org", license: "AGPL-3.0", platforms: ["windows", "macos", "linux", "ios", "android"], tags: ["messaging", "encryption", "privacy"], alternatives_to: ["WhatsApp", "Telegram"], last_update: "2026-01-08", repo_url: "https://github.com/signalapp/Signal-Desktop", is_foss: true, stars: 14500, maturity: "stable" },
    { id: "session", category: "privacy", name: "Session", tagline: "Anonymous messenger", description: "End-to-end encrypted messenger that minimizes metadata.", website: "https://getsession.org", license: "GPL-3.0", platforms: ["windows", "macos", "linux", "ios", "android"], tags: ["messaging", "privacy", "anonymous"], alternatives_to: ["Signal"], last_update: "2025-12-15", repo_url: "https://github.com/oxen-io/session-desktop", is_foss: true, stars: 1500, maturity: "stable" },
    { id: "briar", category: "privacy", name: "Briar", tagline: "Secure messenger", description: "Secure messaging app designed for activists and journalists.", website: "https://briarproject.org", license: "GPL-3.0", platforms: ["android"], tags: ["messaging", "privacy", "p2p"], alternatives_to: ["Signal"], last_update: "2025-11-20", repo_url: "https://code.briarproject.org/briar/briar", is_foss: true, stars: 500, maturity: "stable" },

    // ==================== MORE FILE TOOLS ====================
    { id: "filezilla", category: "file", name: "FileZilla", tagline: "FTP client", description: "Free, open-source FTP solution supporting FTP, FTPS, and SFTP.", website: "https://filezilla-project.org", license: "GPL-2.0", platforms: ["windows", "macos", "linux"], tags: ["ftp", "sftp", "transfer"], alternatives_to: ["Cyberduck"], last_update: "2025-12-20", repo_url: "https://svn.filezilla-project.org/filezilla/FileZilla3", is_foss: true, stars: 1000, maturity: "mature" },
    { id: "cyberduck", category: "file", name: "Cyberduck", tagline: "Cloud storage browser", description: "Libre server and cloud storage browser for Mac and Windows.", website: "https://cyberduck.io", license: "GPL-3.0", platforms: ["windows", "macos"], tags: ["cloud", "ftp", "s3"], alternatives_to: ["FileZilla"], last_update: "2025-12-15", repo_url: "https://github.com/iterate-ch/cyberduck", is_foss: true, stars: 3200, maturity: "stable" },
    { id: "winscp", category: "file", name: "WinSCP", tagline: "SFTP client", description: "Popular SFTP client and FTP client for Windows.", website: "https://winscp.net", license: "GPL-3.0", platforms: ["windows"], tags: ["sftp", "ftp", "scp"], alternatives_to: ["FileZilla"], last_update: "2025-12-20", repo_url: "https://github.com/winscp/winscp", is_foss: true, stars: 2500, maturity: "mature" },
    { id: "7zip", category: "file", name: "7-Zip", tagline: "File archiver", description: "Free and open-source file archiver with high compression ratio.", website: "https://www.7-zip.org", license: "LGPL-2.1", platforms: ["windows", "linux"], tags: ["compression", "archiver", "7z"], alternatives_to: ["WinRAR"], last_update: "2025-12-15", repo_url: "https://github.com/ip7z/7zip", is_foss: true, stars: 500, maturity: "mature" },
    { id: "peazip", category: "file", name: "PeaZip", tagline: "File archiver", description: "Free file archiver utility supporting 200+ archive formats.", website: "https://peazip.github.io", license: "LGPL-3.0", platforms: ["windows", "linux"], tags: ["compression", "archiver", "multi-format"], alternatives_to: ["7-Zip"], last_update: "2025-12-20", repo_url: "https://github.com/peazip/PeaZip", is_foss: true, stars: 2000, maturity: "stable" },
    { id: "freefilesync", category: "file", name: "FreeFileSync", tagline: "File synchronization", description: "Open-source folder comparison and synchronization software.", website: "https://freefilesync.org", license: "GPL-3.0", platforms: ["windows", "macos", "linux"], tags: ["sync", "backup", "comparison"], alternatives_to: [], last_update: "2025-12-15", repo_url: "https://github.com/nickvergessen/FreeFileSync", is_foss: true, stars: 500, maturity: "stable" },
    { id: "double-commander", category: "file", name: "Double Commander", tagline: "File manager", description: "Cross-platform open-source file manager with two panels.", website: "https://doublecmd.sourceforge.io", license: "GPL-2.0", platforms: ["windows", "macos", "linux"], tags: ["file-manager", "dual-pane", "commander"], alternatives_to: ["Total Commander"], last_update: "2025-11-20", repo_url: "https://github.com/doublecmd/doublecmd", is_foss: true, stars: 2500, maturity: "stable" },
    { id: "spacedrive", category: "file", name: "Spacedrive", tagline: "File explorer", description: "Cross-platform file explorer powered by a virtual distributed filesystem.", website: "https://spacedrive.com", license: "AGPL-3.0", platforms: ["windows", "macos", "linux"], tags: ["file-manager", "distributed", "modern"], alternatives_to: ["Finder", "Explorer"], last_update: "2025-12-20", repo_url: "https://github.com/spacedriveapp/spacedrive", is_foss: true, stars: 32000, maturity: "growing" },
    { id: "files", category: "file", name: "Files", tagline: "Modern file manager", description: "Modern file manager for Windows with tabs and dual pane.", website: "https://files.community", license: "MIT", platforms: ["windows"], tags: ["file-manager", "modern", "tabs"], alternatives_to: ["Windows Explorer"], last_update: "2025-12-15", repo_url: "https://github.com/files-community/Files", is_foss: true, stars: 34000, maturity: "stable" },

    // ==================== MORE MEDIA PLAYERS ====================
    { id: "vlc", category: "media", name: "VLC", tagline: "Media player", description: "Free and open-source cross-platform multimedia player.", website: "https://www.videolan.org/vlc", license: "GPL-2.0", platforms: ["windows", "macos", "linux", "ios", "android"], tags: ["video", "audio", "streaming"], alternatives_to: [], last_update: "2025-12-20", repo_url: "https://github.com/videolan/vlc", is_foss: true, stars: 14000, maturity: "mature" },
    { id: "mpv", category: "media", name: "mpv", tagline: "Media player", description: "Free, open-source, and cross-platform media player.", website: "https://mpv.io", license: "GPL-2.0", platforms: ["windows", "macos", "linux"], tags: ["video", "audio", "minimal"], alternatives_to: ["VLC"], last_update: "2025-12-15", repo_url: "https://github.com/mpv-player/mpv", is_foss: true, stars: 28000, maturity: "stable" },
    { id: "jellyfin", category: "media", name: "Jellyfin", tagline: "Media server", description: "Free software media system for streaming your media.", website: "https://jellyfin.org", license: "GPL-2.0", platforms: ["windows", "macos", "linux", "self-hosted"], tags: ["media-server", "streaming", "self-hosted"], alternatives_to: ["Plex", "Emby"], last_update: "2026-01-10", repo_url: "https://github.com/jellyfin/jellyfin", is_foss: true, stars: 35000, maturity: "stable" },
    { id: "plex", category: "media", name: "Plex", tagline: "Media server", description: "Media server software to organize and stream your media.", website: "https://www.plex.tv", license: "Proprietary", platforms: ["windows", "macos", "linux", "ios", "android"], tags: ["media-server", "streaming", "organization"], alternatives_to: ["Jellyfin"], last_update: "2026-01-08", is_foss: false, maturity: "mature" },
    { id: "kodi", category: "media", name: "Kodi", tagline: "Media center", description: "Free and open-source media player and entertainment hub.", website: "https://kodi.tv", license: "GPL-2.0", platforms: ["windows", "macos", "linux", "ios", "android"], tags: ["media-center", "entertainment", "addons"], alternatives_to: ["Plex"], last_update: "2025-12-20", repo_url: "https://github.com/xbmc/xbmc", is_foss: true, stars: 18000, maturity: "mature" },
    { id: "stremio", category: "media", name: "Stremio", tagline: "Media center", description: "Modern media center with addons for streaming content.", website: "https://www.stremio.com", license: "GPL-3.0", platforms: ["windows", "macos", "linux", "ios", "android"], tags: ["streaming", "media-center", "addons"], alternatives_to: ["Kodi"], last_update: "2025-12-15", repo_url: "https://github.com/Stremio/stremio-shell", is_foss: true, stars: 2500, maturity: "stable" },
    { id: "navidrome", category: "media", name: "Navidrome", tagline: "Music server", description: "Modern music server and streamer compatible with Subsonic/Airsonic.", website: "https://www.navidrome.org", license: "GPL-3.0", platforms: ["windows", "macos", "linux", "self-hosted"], tags: ["music", "streaming", "self-hosted"], alternatives_to: ["Plex"], last_update: "2025-12-20", repo_url: "https://github.com/navidrome/navidrome", is_foss: true, stars: 12000, maturity: "stable" },
    { id: "funkwhale", category: "media", name: "Funkwhale", tagline: "Music server", description: "Modern, self-hosted, free and open-source music server.", website: "https://funkwhale.audio", license: "AGPL-3.0", platforms: ["self-hosted"], tags: ["music", "federated", "self-hosted"], alternatives_to: ["Spotify"], last_update: "2025-12-15", repo_url: "https://dev.funkwhale.audio/funkwhale/funkwhale", is_foss: true, stars: 1500, maturity: "stable" },

    // ==================== MORE EBOOK TOOLS ====================
    { id: "calibre", category: "ebook", name: "Calibre", tagline: "E-book management", description: "Powerful and easy to use e-book manager.", website: "https://calibre-ebook.com", license: "GPL-3.0", platforms: ["windows", "macos", "linux"], tags: ["ebook", "library", "conversion"], alternatives_to: [], last_update: "2025-12-20", repo_url: "https://github.com/kovidgoyal/calibre", is_foss: true, stars: 19500, maturity: "mature" },
    { id: "calibre-web", category: "ebook", name: "Calibre-Web", tagline: "Web-based ebook browser", description: "Web app providing a clean interface for browsing, reading and downloading eBooks.", website: "https://github.com/janeczku/calibre-web", license: "GPL-3.0", platforms: ["self-hosted"], tags: ["ebook", "web", "calibre"], alternatives_to: [], last_update: "2025-12-15", repo_url: "https://github.com/janeczku/calibre-web", is_foss: true, stars: 13000, maturity: "stable" },
    { id: "kavita", category: "ebook", name: "Kavita", tagline: "Reading server", description: "Fast, feature-rich, cross-platform reading server.", website: "https://www.kavitareader.com", license: "GPL-3.0", platforms: ["windows", "macos", "linux", "self-hosted"], tags: ["ebook", "manga", "comics"], alternatives_to: ["Calibre-Web"], last_update: "2025-12-20", repo_url: "https://github.com/Kareadita/Kavita", is_foss: true, stars: 6500, maturity: "stable" },
    { id: "komga", category: "ebook", name: "Komga", tagline: "Comics/manga server", description: "Media server for comics/mangas/BDs with API and OPDS support.", website: "https://komga.org", license: "MIT", platforms: ["windows", "macos", "linux", "self-hosted"], tags: ["comics", "manga", "server"], alternatives_to: [], last_update: "2025-12-15", repo_url: "https://github.com/gotson/komga", is_foss: true, stars: 4000, maturity: "stable" },
    { id: "foliate", category: "ebook", name: "Foliate", tagline: "E-book reader", description: "Modern GTK e-book reader for Linux.", website: "https://johnfactotum.github.io/foliate", license: "GPL-3.0", platforms: ["linux"], tags: ["ebook", "reader", "gtk"], alternatives_to: [], last_update: "2025-11-20", repo_url: "https://github.com/johnfactotum/foliate", is_foss: true, stars: 5800, maturity: "stable" },
    { id: "thorium", category: "ebook", name: "Thorium Reader", tagline: "EPUB reader", description: "Cross-platform desktop reading application for EPUB.", website: "https://www.edrlab.org/software/thorium-reader", license: "BSD-3-Clause", platforms: ["windows", "macos", "linux"], tags: ["ebook", "epub", "accessibility"], alternatives_to: [], last_update: "2025-12-20", repo_url: "https://github.com/edrlab/thorium-reader", is_foss: true, stars: 1800, maturity: "stable" },

    // ==================== MORE ENCRYPTION TOOLS ====================
    { id: "veracrypt", category: "encryption", name: "VeraCrypt", tagline: "Disk encryption", description: "Free open-source disk encryption software.", website: "https://www.veracrypt.fr", license: "Apache-2.0", platforms: ["windows", "macos", "linux"], tags: ["encryption", "disk", "security"], alternatives_to: ["BitLocker"], last_update: "2025-12-15", repo_url: "https://github.com/veracrypt/VeraCrypt", is_foss: true, stars: 6500, maturity: "stable" },
    { id: "cryptomator", category: "encryption", name: "Cryptomator", tagline: "Cloud encryption", description: "Multi-platform transparent client-side encryption of your files in the cloud.", website: "https://cryptomator.org", license: "GPL-3.0", platforms: ["windows", "macos", "linux", "ios", "android"], tags: ["encryption", "cloud", "privacy"], alternatives_to: [], last_update: "2025-12-20", repo_url: "https://github.com/cryptomator/cryptomator", is_foss: true, stars: 12000, maturity: "stable" },
    { id: "age", category: "encryption", name: "age", tagline: "File encryption", description: "Simple, modern and secure file encryption tool.", website: "https://age-encryption.org", license: "BSD-3-Clause", platforms: ["windows", "macos", "linux"], tags: ["encryption", "files", "modern"], alternatives_to: ["GPG"], last_update: "2025-12-15", repo_url: "https://github.com/FiloSottile/age", is_foss: true, stars: 17000, maturity: "stable" },
    { id: "gpg4win", category: "encryption", name: "Gpg4win", tagline: "Email encryption", description: "Email and file encryption package for Windows.", website: "https://www.gpg4win.org", license: "GPL-3.0", platforms: ["windows"], tags: ["encryption", "email", "gpg"], alternatives_to: [], last_update: "2025-11-20", repo_url: "https://github.com/gpg/gpg4win", is_foss: true, stars: 500, maturity: "mature" },
    { id: "picocrypt", category: "encryption", name: "Picocrypt", tagline: "File encryption", description: "Very small, very simple, yet very secure encryption tool.", website: "https://github.com/HACKERALERT/Picocrypt", license: "GPL-3.0", platforms: ["windows", "macos", "linux"], tags: ["encryption", "simple", "secure"], alternatives_to: ["VeraCrypt"], last_update: "2025-12-20", repo_url: "https://github.com/HACKERALERT/Picocrypt", is_foss: true, stars: 2500, maturity: "stable" },

    // ==================== MORE HEALTH & WELLNESS ====================
    { id: "openfoodfacts", category: "health", name: "Open Food Facts", tagline: "Food database", description: "Collaborative, free and open database of food products.", website: "https://world.openfoodfacts.org", license: "AGPL-3.0", platforms: ["web", "ios", "android"], tags: ["food", "nutrition", "database"], alternatives_to: [], last_update: "2025-12-20", repo_url: "https://github.com/openfoodfacts/openfoodfacts-server", is_foss: true, stars: 1500, maturity: "stable" },
    { id: "wger", category: "health", name: "wger", tagline: "Workout manager", description: "Free, open-source web application for managing workouts.", website: "https://wger.de", license: "AGPL-3.0", platforms: ["web", "self-hosted", "android"], tags: ["fitness", "workout", "tracking"], alternatives_to: [], last_update: "2025-12-15", repo_url: "https://github.com/wger-project/wger", is_foss: true, stars: 3000, maturity: "stable" },
    { id: "openscale", category: "health", name: "openScale", tagline: "Weight tracking", description: "Open-source weight and body metrics tracker.", website: "https://github.com/oliexdev/openScale", license: "GPL-3.0", platforms: ["android"], tags: ["weight", "health", "tracking"], alternatives_to: [], last_update: "2025-11-20", repo_url: "https://github.com/oliexdev/openScale", is_foss: true, stars: 1500, maturity: "stable" },
    { id: "gadgetbridge", category: "health", name: "Gadgetbridge", tagline: "Fitness tracker companion", description: "Free and cloudless replacement for your gadget vendors' closed source Android applications.", website: "https://gadgetbridge.org", license: "AGPL-3.0", platforms: ["android"], tags: ["fitness", "wearables", "privacy"], alternatives_to: [], last_update: "2025-12-20", repo_url: "https://codeberg.org/Freeyourgadget/Gadgetbridge", is_foss: true, stars: 3000, maturity: "stable" },

    // ==================== MORE GEOGRAPHIC/GIS ====================
    { id: "qgis", category: "geographic", name: "QGIS", tagline: "GIS application", description: "Free and open-source geographic information system.", website: "https://qgis.org", license: "GPL-2.0", platforms: ["windows", "macos", "linux"], tags: ["gis", "mapping", "analysis"], alternatives_to: ["ArcGIS"], last_update: "2025-12-20", repo_url: "https://github.com/qgis/QGIS", is_foss: true, stars: 10000, maturity: "mature" },
    { id: "openstreetmap", category: "geographic", name: "OpenStreetMap", tagline: "Free world map", description: "Free, editable map of the whole world.", website: "https://www.openstreetmap.org", license: "ODbL", platforms: ["web"], tags: ["maps", "crowdsourced", "open-data"], alternatives_to: ["Google Maps"], last_update: "2026-01-15", repo_url: "https://github.com/openstreetmap/openstreetmap-website", is_foss: true, stars: 2200, maturity: "mature" },
    { id: "osmand", category: "geographic", name: "OsmAnd", tagline: "Offline maps", description: "Global mobile map viewing and navigation for offline and online maps.", website: "https://osmand.net", license: "GPL-3.0", platforms: ["ios", "android"], tags: ["maps", "offline", "navigation"], alternatives_to: ["Google Maps"], last_update: "2025-12-20", repo_url: "https://github.com/osmandapp/OsmAnd", is_foss: true, stars: 4500, maturity: "stable" },
    { id: "organicmaps", category: "geographic", name: "Organic Maps", tagline: "Offline maps", description: "Free, community-driven maps app with privacy focus.", website: "https://organicmaps.app", license: "Apache-2.0", platforms: ["ios", "android"], tags: ["maps", "offline", "privacy"], alternatives_to: ["Google Maps"], last_update: "2025-12-15", repo_url: "https://github.com/organicmaps/organicmaps", is_foss: true, stars: 9500, maturity: "stable" },
    { id: "marble", category: "geographic", name: "Marble", tagline: "Virtual globe", description: "Virtual globe and world atlas for KDE.", website: "https://marble.kde.org", license: "LGPL-2.1", platforms: ["windows", "macos", "linux"], tags: ["globe", "maps", "education"], alternatives_to: ["Google Earth"], last_update: "2025-11-20", repo_url: "https://invent.kde.org/education/marble", is_foss: true, stars: 500, maturity: "stable" },

    // ==================== MORE FINANCE TOOLS ====================
    { id: "gnucash", category: "finance", name: "GnuCash", tagline: "Personal finance", description: "Personal and small-business financial-accounting software.", website: "https://www.gnucash.org", license: "GPL-2.0", platforms: ["windows", "macos", "linux"], tags: ["accounting", "finance", "bookkeeping"], alternatives_to: ["Quicken"], last_update: "2025-12-20", repo_url: "https://github.com/Gnucash/gnucash", is_foss: true, stars: 3200, maturity: "mature" },
    { id: "homebank", category: "finance", name: "HomeBank", tagline: "Personal finance", description: "Free personal finance software for managing accounts.", website: "http://homebank.free.fr", license: "GPL-2.0", platforms: ["windows", "macos", "linux"], tags: ["finance", "budgeting", "personal"], alternatives_to: ["Quicken"], last_update: "2025-11-20", repo_url: "https://github.com/cyosp/homebank", is_foss: true, stars: 300, maturity: "stable" },
    { id: "firefly-iii", category: "finance", name: "Firefly III", tagline: "Personal finance manager", description: "Free and open-source personal finance manager.", website: "https://www.firefly-iii.org", license: "AGPL-3.0", platforms: ["web", "self-hosted"], tags: ["finance", "budgeting", "self-hosted"], alternatives_to: ["YNAB", "Mint"], last_update: "2025-12-20", repo_url: "https://github.com/firefly-iii/firefly-iii", is_foss: true, stars: 16000, maturity: "stable" },
    { id: "actualbudget", category: "finance", name: "Actual Budget", tagline: "Budgeting app", description: "Local-first personal finance tool with sync.", website: "https://actualbudget.com", license: "MIT", platforms: ["windows", "macos", "linux", "web"], tags: ["budgeting", "local-first", "sync"], alternatives_to: ["YNAB"], last_update: "2025-12-15", repo_url: "https://github.com/actualbudget/actual", is_foss: true, stars: 14000, maturity: "stable" },
    { id: "maybe", category: "finance", name: "Maybe", tagline: "Personal finance", description: "Open-source personal finance and wealth management app.", website: "https://maybe.co", license: "AGPL-3.0", platforms: ["web", "self-hosted"], tags: ["finance", "wealth", "investing"], alternatives_to: ["Personal Capital"], last_update: "2025-12-20", repo_url: "https://github.com/maybe-finance/maybe", is_foss: true, stars: 32000, maturity: "growing" },
    { id: "ledger", category: "finance", name: "Ledger", tagline: "Command-line accounting", description: "Double-entry accounting system with a command-line interface.", website: "https://www.ledger-cli.org", license: "BSD-3-Clause", platforms: ["windows", "macos", "linux"], tags: ["accounting", "cli", "plain-text"], alternatives_to: [], last_update: "2025-10-15", repo_url: "https://github.com/ledger/ledger", is_foss: true, stars: 5200, maturity: "stable" },
    { id: "beancount", category: "finance", name: "Beancount", tagline: "Plain text accounting", description: "Double-entry bookkeeping computer language.", website: "https://beancount.github.io", license: "GPL-2.0", platforms: ["windows", "macos", "linux"], tags: ["accounting", "plain-text", "python"], alternatives_to: ["Ledger"], last_update: "2025-12-15", repo_url: "https://github.com/beancount/beancount", is_foss: true, stars: 3500, maturity: "stable" },
];

module.exports = { bonusTools };
