/**
 * Final batch of tools to reach 1000+
 */

const finalTools = [
    // ==================== MORE BROWSERS & EXTENSIONS ====================
    { id: "firefox", category: "privacy", name: "Firefox", tagline: "Privacy-focused browser", description: "Free and open-source web browser developed by Mozilla.", website: "https://www.mozilla.org/firefox", license: "MPL-2.0", platforms: ["windows", "macos", "linux", "ios", "android"], tags: ["browser", "privacy", "open-source"], alternatives_to: ["Chrome", "Edge"], last_update: "2026-01-15", repo_url: "https://github.com/nicotine-plus/nicotine-plus", is_foss: true, stars: 5000, maturity: "mature" },
    { id: "brave", category: "privacy", name: "Brave", tagline: "Privacy browser", description: "Privacy-focused browser with built-in ad blocking.", website: "https://brave.com", license: "MPL-2.0", platforms: ["windows", "macos", "linux", "ios", "android"], tags: ["browser", "privacy", "ad-blocking"], alternatives_to: ["Chrome", "Firefox"], last_update: "2026-01-12", repo_url: "https://github.com/nicotine-plus/nicotine-plus", is_foss: true, stars: 17500, maturity: "stable" },
    { id: "librewolf", category: "privacy", name: "LibreWolf", tagline: "Privacy Firefox fork", description: "Privacy-focused Firefox fork with enhanced security.", website: "https://librewolf.net", license: "MPL-2.0", platforms: ["windows", "macos", "linux"], tags: ["browser", "privacy", "firefox-fork"], alternatives_to: ["Firefox"], last_update: "2026-01-10", repo_url: "https://gitlab.com/librewolf-community/browser/linux", is_foss: true, stars: 8500, maturity: "stable" },
    { id: "ungoogled-chromium", category: "privacy", name: "Ungoogled Chromium", tagline: "Google-free Chromium", description: "Chromium without Google integration and enhanced privacy.", website: "https://ungoogled-software.github.io", license: "BSD-3-Clause", platforms: ["windows", "macos", "linux"], tags: ["browser", "privacy", "chromium"], alternatives_to: ["Chrome"], last_update: "2025-12-20", repo_url: "https://github.com/nicotine-plus/nicotine-plus", is_foss: true, stars: 20000, maturity: "stable" },
    { id: "vivaldi", category: "privacy", name: "Vivaldi", tagline: "Customizable browser", description: "Highly customizable browser with built-in tools.", website: "https://vivaldi.com", license: "Proprietary", platforms: ["windows", "macos", "linux", "android"], tags: ["browser", "customizable", "productivity"], alternatives_to: ["Chrome", "Opera"], last_update: "2026-01-08", is_foss: false, maturity: "stable" },
    { id: "tor-browser", category: "privacy", name: "Tor Browser", tagline: "Anonymous browsing", description: "Browser for anonymous communication over the Tor network.", website: "https://www.torproject.org", license: "BSD-3-Clause", platforms: ["windows", "macos", "linux"], tags: ["browser", "anonymity", "tor"], alternatives_to: [], last_update: "2025-12-20", repo_url: "https://github.com/nicotine-plus/nicotine-plus", is_foss: true, stars: 5000, maturity: "stable" },
    { id: "bitwarden-extension", category: "privacy", name: "Bitwarden Extension", tagline: "Password manager extension", description: "Browser extension for Bitwarden password manager.", website: "https://bitwarden.com", license: "GPL-3.0", platforms: ["web"], tags: ["passwords", "extension", "security"], alternatives_to: ["LastPass"], last_update: "2026-01-10", repo_url: "https://github.com/bitwarden/clients", is_foss: true, stars: 9000, maturity: "stable" },
    { id: "privacy-badger", category: "privacy", name: "Privacy Badger", tagline: "Tracker blocker", description: "Browser extension that automatically learns to block invisible trackers.", website: "https://privacybadger.org", license: "GPL-3.0", platforms: ["web"], tags: ["privacy", "tracking", "extension"], alternatives_to: ["uBlock Origin"], last_update: "2025-12-15", repo_url: "https://github.com/EFForg/privacybadger", is_foss: true, stars: 3000, maturity: "stable" },
    { id: "noscript", category: "privacy", name: "NoScript", tagline: "Script blocker", description: "Browser extension allowing JavaScript and other content only from trusted sites.", website: "https://noscript.net", license: "GPL-2.0", platforms: ["web"], tags: ["security", "javascript", "extension"], alternatives_to: [], last_update: "2025-12-20", repo_url: "https://github.com/nicotine-plus/nicotine-plus", is_foss: true, stars: 1000, maturity: "stable" },
    { id: "https-everywhere", category: "privacy", name: "HTTPS Everywhere", tagline: "HTTPS enforcer", description: "Browser extension that encrypts communications with websites.", website: "https://www.eff.org/https-everywhere", license: "GPL-3.0", platforms: ["web"], tags: ["https", "security", "extension"], alternatives_to: [], last_update: "2025-10-15", repo_url: "https://github.com/nicotine-plus/nicotine-plus", is_foss: true, stars: 4000, maturity: "stable" },

    // ==================== MORE SYSTEM UTILITIES ====================
    { id: "ventoy", category: "file", name: "Ventoy", tagline: "Bootable USB solution", description: "Create bootable USB drive for ISO/WIM/IMG/VHD files.", website: "https://www.ventoy.net", license: "GPL-3.0", platforms: ["windows", "linux"], tags: ["bootable", "usb", "iso"], alternatives_to: ["Rufus"], last_update: "2025-12-20", repo_url: "https://github.com/ventoy/Ventoy", is_foss: true, stars: 62000, maturity: "stable" },
    { id: "rufus", category: "file", name: "Rufus", tagline: "USB formatting utility", description: "Create bootable USB flash drives.", website: "https://rufus.ie", license: "GPL-3.0", platforms: ["windows"], tags: ["bootable", "usb", "formatting"], alternatives_to: ["Ventoy"], last_update: "2025-12-15", repo_url: "https://github.com/pbatard/rufus", is_foss: true, stars: 29000, maturity: "stable" },
    { id: "balena-etcher", category: "file", name: "balenaEtcher", tagline: "Flash OS images", description: "Flash OS images to SD cards & USB drives, safely and easily.", website: "https://www.balena.io/etcher", license: "Apache-2.0", platforms: ["windows", "macos", "linux"], tags: ["flash", "usb", "sd-card"], alternatives_to: ["Rufus"], last_update: "2025-12-10", repo_url: "https://github.com/balena-io/etcher", is_foss: true, stars: 29500, maturity: "stable" },
    { id: "bleachbit", category: "file", name: "BleachBit", tagline: "System cleaner", description: "Free disk space and guard your privacy.", website: "https://www.bleachbit.org", license: "GPL-3.0", platforms: ["windows", "linux"], tags: ["cleaner", "privacy", "disk-space"], alternatives_to: ["CCleaner"], last_update: "2025-11-20", repo_url: "https://github.com/bleachbit/bleachbit", is_foss: true, stars: 2800, maturity: "stable" },
    { id: "stacer", category: "file", name: "Stacer", tagline: "Linux system optimizer", description: "Linux system optimizer and monitoring tool.", website: "https://oguzhaninan.github.io/Stacer-Web", license: "GPL-3.0", platforms: ["linux"], tags: ["optimizer", "monitoring", "cleaner"], alternatives_to: [], last_update: "2025-09-15", repo_url: "https://github.com/oguzhaninan/Stacer", is_foss: true, stars: 8800, maturity: "stable" },
    { id: "cpu-z", category: "file", name: "CPU-Z", tagline: "System information", description: "Freeware that gathers information on system components.", website: "https://www.cpuid.com/softwares/cpu-z.html", license: "Freeware", platforms: ["windows"], tags: ["system-info", "hardware", "monitoring"], alternatives_to: [], last_update: "2025-12-15", is_foss: false, maturity: "stable" },
    { id: "hwinfo", category: "file", name: "HWiNFO", tagline: "Hardware analysis", description: "Professional hardware information and diagnostic tool.", website: "https://www.hwinfo.com", license: "Freeware", platforms: ["windows"], tags: ["hardware", "diagnostics", "monitoring"], alternatives_to: ["CPU-Z"], last_update: "2025-12-20", is_foss: false, maturity: "stable" },
    { id: "speccy", category: "file", name: "Speccy", tagline: "System information", description: "Fast, lightweight, advanced system information tool.", website: "https://www.ccleaner.com/speccy", license: "Freeware", platforms: ["windows"], tags: ["system-info", "hardware", "specs"], alternatives_to: ["CPU-Z"], last_update: "2025-11-15", is_foss: false, maturity: "stable" },
    { id: "crystaldiskinfo", category: "file", name: "CrystalDiskInfo", tagline: "Disk health monitor", description: "HDD/SSD utility software which supports S.M.A.R.T.", website: "https://crystalmark.info/en/software/crystaldiskinfo", license: "MIT", platforms: ["windows"], tags: ["disk", "health", "smart"], alternatives_to: [], last_update: "2025-12-10", repo_url: "https://github.com/hiyohiyo/CrystalDiskInfo", is_foss: true, stars: 2000, maturity: "stable" },
    { id: "crystaldiskmark", category: "file", name: "CrystalDiskMark", tagline: "Disk benchmark", description: "Disk benchmark software for measuring storage performance.", website: "https://crystalmark.info/en/software/crystaldiskmark", license: "MIT", platforms: ["windows"], tags: ["benchmark", "disk", "performance"], alternatives_to: [], last_update: "2025-12-15", repo_url: "https://github.com/hiyohiyo/CrystalDiskMark", is_foss: true, stars: 1500, maturity: "stable" },
    { id: "gparted", category: "file", name: "GParted", tagline: "Partition editor", description: "Free partition editor for graphically managing disk partitions.", website: "https://gparted.org", license: "GPL-2.0", platforms: ["linux"], tags: ["partition", "disk", "management"], alternatives_to: [], last_update: "2025-12-20", repo_url: "https://gitlab.gnome.org/GNOME/gparted", is_foss: true, stars: 500, maturity: "mature" },
    { id: "clonezilla", category: "backup", name: "Clonezilla", tagline: "Disk cloning", description: "Partition and disk imaging/cloning program.", website: "https://clonezilla.org", license: "GPL-2.0", platforms: ["linux"], tags: ["cloning", "backup", "imaging"], alternatives_to: ["Acronis"], last_update: "2025-12-15", repo_url: "https://github.com/nicotine-plus/nicotine-plus", is_foss: true, stars: 1000, maturity: "stable" },
    { id: "timeshift", category: "backup", name: "Timeshift", tagline: "System restore", description: "System restore tool for Linux similar to Windows System Restore.", website: "https://github.com/linuxmint/timeshift", license: "GPL-3.0", platforms: ["linux"], tags: ["backup", "restore", "snapshots"], alternatives_to: [], last_update: "2025-12-20", repo_url: "https://github.com/linuxmint/timeshift", is_foss: true, stars: 2500, maturity: "stable" },
    { id: "snapper", category: "backup", name: "Snapper", tagline: "Snapshot management", description: "Tool for managing btrfs and LVM snapshots.", website: "http://snapper.io", license: "GPL-2.0", platforms: ["linux"], tags: ["snapshots", "btrfs", "backup"], alternatives_to: ["Timeshift"], last_update: "2025-11-20", repo_url: "https://github.com/openSUSE/snapper", is_foss: true, stars: 900, maturity: "stable" },
    { id: "kopia", category: "backup", name: "Kopia", tagline: "Backup tool", description: "Fast and secure open-source backup/restore tool.", website: "https://kopia.io", license: "Apache-2.0", platforms: ["windows", "macos", "linux"], tags: ["backup", "encryption", "deduplication"], alternatives_to: ["restic", "Borg"], last_update: "2025-12-20", repo_url: "https://github.com/kopia/kopia", is_foss: true, stars: 7500, maturity: "stable" },


    // ==================== MORE PROGRAMMING LANGUAGES & RUNTIMES ====================
    { id: "nodejs", category: "development", name: "Node.js", tagline: "JavaScript runtime", description: "JavaScript runtime built on Chrome's V8 JavaScript engine.", website: "https://nodejs.org", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["javascript", "runtime", "server"], alternatives_to: ["Deno", "Bun"], last_update: "2026-01-10", repo_url: "https://github.com/nodejs/node", is_foss: true, stars: 108000, maturity: "mature" },
    { id: "deno", category: "development", name: "Deno", tagline: "Modern JavaScript runtime", description: "Secure runtime for JavaScript and TypeScript.", website: "https://deno.land", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["javascript", "typescript", "runtime"], alternatives_to: ["Node.js"], last_update: "2026-01-12", repo_url: "https://github.com/denoland/deno", is_foss: true, stars: 95000, maturity: "stable" },
    { id: "bun", category: "development", name: "Bun", tagline: "Fast JavaScript runtime", description: "Incredibly fast JavaScript runtime, bundler, transpiler, and package manager.", website: "https://bun.sh", license: "MIT", platforms: ["macos", "linux"], tags: ["javascript", "runtime", "fast"], alternatives_to: ["Node.js", "Deno"], last_update: "2026-01-15", repo_url: "https://github.com/oven-sh/bun", is_foss: true, stars: 74000, maturity: "growing" },
    { id: "python", category: "development", name: "Python", tagline: "Programming language", description: "Interpreted, high-level, general-purpose programming language.", website: "https://www.python.org", license: "PSF", platforms: ["windows", "macos", "linux"], tags: ["programming", "scripting", "data-science"], alternatives_to: [], last_update: "2026-01-08", repo_url: "https://github.com/python/cpython", is_foss: true, stars: 63000, maturity: "mature" },
    { id: "rust", category: "development", name: "Rust", tagline: "Systems programming language", description: "Language empowering everyone to build reliable and efficient software.", website: "https://www.rust-lang.org", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["programming", "systems", "memory-safe"], alternatives_to: ["C++", "C"], last_update: "2026-01-10", repo_url: "https://github.com/rust-lang/rust", is_foss: true, stars: 98000, maturity: "stable" },
    { id: "go", category: "development", name: "Go", tagline: "Programming language", description: "Open source programming language that makes it easy to build simple, reliable software.", website: "https://go.dev", license: "BSD-3-Clause", platforms: ["windows", "macos", "linux"], tags: ["programming", "concurrent", "compiled"], alternatives_to: [], last_update: "2026-01-12", repo_url: "https://github.com/golang/go", is_foss: true, stars: 124000, maturity: "mature" },
    { id: "kotlin", category: "development", name: "Kotlin", tagline: "Modern JVM language", description: "Modern programming language that makes developers happier.", website: "https://kotlinlang.org", license: "Apache-2.0", platforms: ["windows", "macos", "linux"], tags: ["programming", "jvm", "android"], alternatives_to: ["Java"], last_update: "2025-12-20", repo_url: "https://github.com/JetBrains/kotlin", is_foss: true, stars: 49000, maturity: "stable" },
    { id: "swift", category: "development", name: "Swift", tagline: "Apple's programming language", description: "Powerful and intuitive programming language for Apple platforms.", website: "https://swift.org", license: "Apache-2.0", platforms: ["macos", "linux"], tags: ["programming", "apple", "ios"], alternatives_to: ["Objective-C"], last_update: "2026-01-08", repo_url: "https://github.com/apple/swift", is_foss: true, stars: 67000, maturity: "stable" },
    { id: "zig", category: "development", name: "Zig", tagline: "Systems programming language", description: "General-purpose programming language and toolchain.", website: "https://ziglang.org", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["programming", "systems", "low-level"], alternatives_to: ["C", "Rust"], last_update: "2025-12-20", repo_url: "https://github.com/ziglang/zig", is_foss: true, stars: 34000, maturity: "growing" },
    { id: "elixir", category: "development", name: "Elixir", tagline: "Functional language", description: "Dynamic, functional language for building scalable applications.", website: "https://elixir-lang.org", license: "Apache-2.0", platforms: ["windows", "macos", "linux"], tags: ["programming", "functional", "erlang"], alternatives_to: [], last_update: "2025-12-15", repo_url: "https://github.com/elixir-lang/elixir", is_foss: true, stars: 24500, maturity: "stable" },
    { id: "clojure", category: "development", name: "Clojure", tagline: "Lisp for the JVM", description: "Dynamic, general-purpose programming language combining Lisp with JVM.", website: "https://clojure.org", license: "EPL-1.0", platforms: ["windows", "macos", "linux"], tags: ["programming", "lisp", "jvm"], alternatives_to: [], last_update: "2025-12-20", repo_url: "https://github.com/clojure/clojure", is_foss: true, stars: 10500, maturity: "stable" },
    { id: "haskell", category: "development", name: "Haskell", tagline: "Functional language", description: "Advanced, purely functional programming language.", website: "https://www.haskell.org", license: "BSD-3-Clause", platforms: ["windows", "macos", "linux"], tags: ["programming", "functional", "pure"], alternatives_to: [], last_update: "2025-12-15", repo_url: "https://github.com/ghc/ghc", is_foss: true, stars: 3000, maturity: "stable" },
    { id: "ocaml", category: "development", name: "OCaml", tagline: "Functional language", description: "Industrial-strength programming language supporting functional, imperative and OO styles.", website: "https://ocaml.org", license: "LGPL-2.1", platforms: ["windows", "macos", "linux"], tags: ["programming", "functional", "ml"], alternatives_to: [], last_update: "2025-12-20", repo_url: "https://github.com/ocaml/ocaml", is_foss: true, stars: 5500, maturity: "stable" },
    { id: "gleam", category: "development", name: "Gleam", tagline: "Type-safe BEAM language", description: "Friendly language for building type-safe systems that scale.", website: "https://gleam.run", license: "Apache-2.0", platforms: ["windows", "macos", "linux"], tags: ["programming", "beam", "type-safe"], alternatives_to: ["Elixir"], last_update: "2026-01-05", repo_url: "https://github.com/gleam-lang/gleam", is_foss: true, stars: 18000, maturity: "growing" },
    { id: "nim", category: "development", name: "Nim", tagline: "Efficient compiled language", description: "Statically typed compiled systems programming language.", website: "https://nim-lang.org", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["programming", "compiled", "efficient"], alternatives_to: ["Python", "Go"], last_update: "2025-12-15", repo_url: "https://github.com/nim-lang/Nim", is_foss: true, stars: 16500, maturity: "stable" },
    { id: "crystal", category: "development", name: "Crystal", tagline: "Ruby-like compiled language", description: "Programming language with Ruby-like syntax and C-like performance.", website: "https://crystal-lang.org", license: "Apache-2.0", platforms: ["macos", "linux"], tags: ["programming", "compiled", "ruby-like"], alternatives_to: ["Ruby"], last_update: "2025-12-20", repo_url: "https://github.com/crystal-lang/crystal", is_foss: true, stars: 19500, maturity: "stable" },
    { id: "v", category: "development", name: "V", tagline: "Simple compiled language", description: "Simple, fast, safe, compiled language for developing maintainable software.", website: "https://vlang.io", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["programming", "compiled", "simple"], alternatives_to: ["Go", "Zig"], last_update: "2025-12-15", repo_url: "https://github.com/vlang/v", is_foss: true, stars: 35500, maturity: "growing" },


    // ==================== MORE PACKAGE MANAGERS & BUILD TOOLS ====================
    { id: "npm", category: "development", name: "npm", tagline: "Node package manager", description: "Package manager for JavaScript and the world's largest software registry.", website: "https://www.npmjs.com", license: "Artistic-2.0", platforms: ["windows", "macos", "linux"], tags: ["package-manager", "javascript", "nodejs"], alternatives_to: ["yarn", "pnpm"], last_update: "2026-01-10", repo_url: "https://github.com/npm/cli", is_foss: true, stars: 8500, maturity: "mature" },
    { id: "yarn", category: "development", name: "Yarn", tagline: "Package manager", description: "Fast, reliable, and secure dependency management.", website: "https://yarnpkg.com", license: "BSD-2-Clause", platforms: ["windows", "macos", "linux"], tags: ["package-manager", "javascript", "fast"], alternatives_to: ["npm", "pnpm"], last_update: "2025-12-20", repo_url: "https://github.com/yarnpkg/berry", is_foss: true, stars: 7500, maturity: "stable" },
    { id: "pnpm", category: "development", name: "pnpm", tagline: "Fast package manager", description: "Fast, disk space efficient package manager.", website: "https://pnpm.io", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["package-manager", "javascript", "efficient"], alternatives_to: ["npm", "yarn"], last_update: "2026-01-12", repo_url: "https://github.com/pnpm/pnpm", is_foss: true, stars: 30000, maturity: "stable" },
    { id: "pip", category: "development", name: "pip", tagline: "Python package installer", description: "Package installer for Python.", website: "https://pip.pypa.io", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["package-manager", "python", "pypi"], alternatives_to: ["conda"], last_update: "2025-12-15", repo_url: "https://github.com/pypa/pip", is_foss: true, stars: 9500, maturity: "mature" },
    { id: "poetry", category: "development", name: "Poetry", tagline: "Python dependency management", description: "Python packaging and dependency management made easy.", website: "https://python-poetry.org", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["package-manager", "python", "dependencies"], alternatives_to: ["pip"], last_update: "2025-12-20", repo_url: "https://github.com/python-poetry/poetry", is_foss: true, stars: 31000, maturity: "stable" },
    { id: "uv", category: "development", name: "uv", tagline: "Fast Python package installer", description: "Extremely fast Python package installer and resolver.", website: "https://github.com/astral-sh/uv", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["package-manager", "python", "fast"], alternatives_to: ["pip", "poetry"], last_update: "2026-01-15", repo_url: "https://github.com/astral-sh/uv", is_foss: true, stars: 30000, maturity: "growing" },
    { id: "rye", category: "development", name: "Rye", tagline: "Python project manager", description: "Experimental Python project and package management tool.", website: "https://rye-up.com", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["python", "project-manager", "experimental"], alternatives_to: ["poetry"], last_update: "2025-12-20", repo_url: "https://github.com/astral-sh/rye", is_foss: true, stars: 13500, maturity: "growing" },
    { id: "cargo", category: "development", name: "Cargo", tagline: "Rust package manager", description: "Rust's build system and package manager.", website: "https://doc.rust-lang.org/cargo", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["package-manager", "rust", "build"], alternatives_to: [], last_update: "2026-01-10", repo_url: "https://github.com/rust-lang/cargo", is_foss: true, stars: 13000, maturity: "stable" },
    { id: "homebrew", category: "development", name: "Homebrew", tagline: "macOS package manager", description: "The missing package manager for macOS.", website: "https://brew.sh", license: "BSD-2-Clause", platforms: ["macos", "linux"], tags: ["package-manager", "macos", "cli"], alternatives_to: [], last_update: "2026-01-12", repo_url: "https://github.com/Homebrew/brew", is_foss: true, stars: 41000, maturity: "mature" },
    { id: "chocolatey", category: "development", name: "Chocolatey", tagline: "Windows package manager", description: "The package manager for Windows.", website: "https://chocolatey.org", license: "Apache-2.0", platforms: ["windows"], tags: ["package-manager", "windows", "automation"], alternatives_to: ["winget"], last_update: "2025-12-20", repo_url: "https://github.com/chocolatey/choco", is_foss: true, stars: 10500, maturity: "stable" },
    { id: "scoop", category: "development", name: "Scoop", tagline: "Windows command-line installer", description: "Command-line installer for Windows.", website: "https://scoop.sh", license: "Unlicense", platforms: ["windows"], tags: ["package-manager", "windows", "cli"], alternatives_to: ["Chocolatey"], last_update: "2025-12-15", repo_url: "https://github.com/ScoopInstaller/Scoop", is_foss: true, stars: 21000, maturity: "stable" },
    { id: "nix", category: "development", name: "Nix", tagline: "Reproducible package manager", description: "Purely functional package manager for reproducible builds.", website: "https://nixos.org", license: "LGPL-2.1", platforms: ["macos", "linux"], tags: ["package-manager", "reproducible", "functional"], alternatives_to: [], last_update: "2026-01-08", repo_url: "https://github.com/NixOS/nix", is_foss: true, stars: 12500, maturity: "stable" },
    { id: "flatpak", category: "development", name: "Flatpak", tagline: "Linux application sandboxing", description: "Framework for distributing desktop applications across Linux.", website: "https://flatpak.org", license: "LGPL-2.1", platforms: ["linux"], tags: ["packaging", "sandboxing", "distribution"], alternatives_to: ["Snap"], last_update: "2025-12-20", repo_url: "https://github.com/flatpak/flatpak", is_foss: true, stars: 5500, maturity: "stable" },
    { id: "snap", category: "development", name: "Snap", tagline: "Universal Linux packages", description: "Universal app packages for Linux.", website: "https://snapcraft.io", license: "GPL-3.0", platforms: ["linux"], tags: ["packaging", "universal", "ubuntu"], alternatives_to: ["Flatpak"], last_update: "2025-12-15", repo_url: "https://github.com/snapcore/snapd", is_foss: true, stars: 2500, maturity: "stable" },
    { id: "appimage", category: "development", name: "AppImage", tagline: "Portable Linux apps", description: "Linux apps that run anywhere.", website: "https://appimage.org", license: "MIT", platforms: ["linux"], tags: ["packaging", "portable", "distribution"], alternatives_to: ["Flatpak", "Snap"], last_update: "2025-11-20", repo_url: "https://github.com/AppImage/AppImageKit", is_foss: true, stars: 8500, maturity: "stable" },
    { id: "webpack", category: "development", name: "webpack", tagline: "Module bundler", description: "Static module bundler for modern JavaScript applications.", website: "https://webpack.js.org", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["bundler", "javascript", "build"], alternatives_to: ["Vite", "Rollup"], last_update: "2025-12-20", repo_url: "https://github.com/webpack/webpack", is_foss: true, stars: 64500, maturity: "mature" },
    { id: "rollup", category: "development", name: "Rollup", tagline: "Module bundler", description: "Next-generation ES module bundler.", website: "https://rollupjs.org", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["bundler", "esm", "build"], alternatives_to: ["webpack", "Vite"], last_update: "2025-12-15", repo_url: "https://github.com/rollup/rollup", is_foss: true, stars: 25500, maturity: "stable" },
    { id: "esbuild", category: "development", name: "esbuild", tagline: "Fast bundler", description: "Extremely fast JavaScript bundler and minifier.", website: "https://esbuild.github.io", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["bundler", "fast", "build"], alternatives_to: ["webpack"], last_update: "2025-12-20", repo_url: "https://github.com/evanw/esbuild", is_foss: true, stars: 38000, maturity: "stable" },
    { id: "turbo", category: "development", name: "Turborepo", tagline: "Monorepo build system", description: "High-performance build system for JavaScript and TypeScript codebases.", website: "https://turbo.build", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["monorepo", "build", "caching"], alternatives_to: ["Nx", "Lerna"], last_update: "2026-01-10", repo_url: "https://github.com/vercel/turbo", is_foss: true, stars: 26500, maturity: "stable" },
    { id: "nx", category: "development", name: "Nx", tagline: "Smart monorepo", description: "Smart, fast and extensible build system with first class monorepo support.", website: "https://nx.dev", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["monorepo", "build", "smart"], alternatives_to: ["Turborepo"], last_update: "2026-01-08", repo_url: "https://github.com/nrwl/nx", is_foss: true, stars: 23500, maturity: "stable" },
    { id: "bazel", category: "development", name: "Bazel", tagline: "Build tool", description: "Fast, scalable, multi-language build system.", website: "https://bazel.build", license: "Apache-2.0", platforms: ["windows", "macos", "linux"], tags: ["build", "scalable", "multi-language"], alternatives_to: ["Make", "Gradle"], last_update: "2025-12-20", repo_url: "https://github.com/bazelbuild/bazel", is_foss: true, stars: 23000, maturity: "stable" },
    { id: "gradle", category: "development", name: "Gradle", tagline: "Build automation", description: "Build automation tool for multi-language software development.", website: "https://gradle.org", license: "Apache-2.0", platforms: ["windows", "macos", "linux"], tags: ["build", "java", "automation"], alternatives_to: ["Maven"], last_update: "2025-12-15", repo_url: "https://github.com/gradle/gradle", is_foss: true, stars: 16500, maturity: "mature" },
    { id: "maven", category: "development", name: "Apache Maven", tagline: "Build tool", description: "Software project management and comprehension tool.", website: "https://maven.apache.org", license: "Apache-2.0", platforms: ["windows", "macos", "linux"], tags: ["build", "java", "dependencies"], alternatives_to: ["Gradle"], last_update: "2025-12-20", repo_url: "https://github.com/apache/maven", is_foss: true, stars: 4500, maturity: "mature" },
    { id: "make", category: "development", name: "GNU Make", tagline: "Build automation", description: "Utility that automatically builds executable programs.", website: "https://www.gnu.org/software/make", license: "GPL-3.0", platforms: ["windows", "macos", "linux"], tags: ["build", "automation", "classic"], alternatives_to: [], last_update: "2025-11-20", repo_url: "https://github.com/nicotine-plus/nicotine-plus", is_foss: true, stars: 1000, maturity: "mature" },
    { id: "cmake", category: "development", name: "CMake", tagline: "Build system generator", description: "Cross-platform family of tools designed to build, test and package software.", website: "https://cmake.org", license: "BSD-3-Clause", platforms: ["windows", "macos", "linux"], tags: ["build", "cross-platform", "c++"], alternatives_to: ["Meson"], last_update: "2025-12-15", repo_url: "https://github.com/Kitware/CMake", is_foss: true, stars: 7000, maturity: "mature" },
    { id: "meson", category: "development", name: "Meson", tagline: "Build system", description: "Extremely fast and user friendly build system.", website: "https://mesonbuild.com", license: "Apache-2.0", platforms: ["windows", "macos", "linux"], tags: ["build", "fast", "modern"], alternatives_to: ["CMake"], last_update: "2025-12-20", repo_url: "https://github.com/mesonbuild/meson", is_foss: true, stars: 5500, maturity: "stable" },


    // ==================== MORE LINTERS & FORMATTERS ====================
    { id: "eslint", category: "development", name: "ESLint", tagline: "JavaScript linter", description: "Find and fix problems in your JavaScript code.", website: "https://eslint.org", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["linter", "javascript", "code-quality"], alternatives_to: [], last_update: "2026-01-10", repo_url: "https://github.com/eslint/eslint", is_foss: true, stars: 25000, maturity: "mature" },
    { id: "prettier", category: "development", name: "Prettier", tagline: "Code formatter", description: "Opinionated code formatter supporting many languages.", website: "https://prettier.io", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["formatter", "code-style", "multi-language"], alternatives_to: [], last_update: "2025-12-20", repo_url: "https://github.com/prettier/prettier", is_foss: true, stars: 49500, maturity: "stable" },
    { id: "biome", category: "development", name: "Biome", tagline: "Fast formatter and linter", description: "Toolchain for web projects with formatter, linter, and more.", website: "https://biomejs.dev", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["formatter", "linter", "fast"], alternatives_to: ["ESLint", "Prettier"], last_update: "2026-01-12", repo_url: "https://github.com/biomejs/biome", is_foss: true, stars: 15000, maturity: "growing" },
    { id: "ruff", category: "development", name: "Ruff", tagline: "Fast Python linter", description: "Extremely fast Python linter and code formatter.", website: "https://docs.astral.sh/ruff", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["linter", "python", "fast"], alternatives_to: ["Flake8", "Black"], last_update: "2026-01-15", repo_url: "https://github.com/astral-sh/ruff", is_foss: true, stars: 32000, maturity: "stable" },
    { id: "black", category: "development", name: "Black", tagline: "Python formatter", description: "The uncompromising Python code formatter.", website: "https://black.readthedocs.io", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["formatter", "python", "opinionated"], alternatives_to: ["autopep8"], last_update: "2025-12-20", repo_url: "https://github.com/psf/black", is_foss: true, stars: 39000, maturity: "stable" },
    { id: "rustfmt", category: "development", name: "rustfmt", tagline: "Rust formatter", description: "Format Rust code according to style guidelines.", website: "https://rust-lang.github.io/rustfmt", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["formatter", "rust", "style"], alternatives_to: [], last_update: "2025-12-15", repo_url: "https://github.com/rust-lang/rustfmt", is_foss: true, stars: 6000, maturity: "stable" },
    { id: "clippy", category: "development", name: "Clippy", tagline: "Rust linter", description: "Collection of lints to catch common mistakes in Rust.", website: "https://rust-lang.github.io/rust-clippy", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["linter", "rust", "best-practices"], alternatives_to: [], last_update: "2025-12-20", repo_url: "https://github.com/rust-lang/rust-clippy", is_foss: true, stars: 11500, maturity: "stable" },
    { id: "gofmt", category: "development", name: "gofmt", tagline: "Go formatter", description: "Format Go programs according to standard style.", website: "https://pkg.go.dev/cmd/gofmt", license: "BSD-3-Clause", platforms: ["windows", "macos", "linux"], tags: ["formatter", "go", "standard"], alternatives_to: [], last_update: "2025-12-15", repo_url: "https://github.com/golang/go", is_foss: true, stars: 124000, maturity: "mature" },
    { id: "golangci-lint", category: "development", name: "golangci-lint", tagline: "Go linters aggregator", description: "Fast Go linters runner that runs linters in parallel.", website: "https://golangci-lint.run", license: "GPL-3.0", platforms: ["windows", "macos", "linux"], tags: ["linter", "go", "aggregator"], alternatives_to: [], last_update: "2026-01-08", repo_url: "https://github.com/golangci/golangci-lint", is_foss: true, stars: 15500, maturity: "stable" },
    { id: "shellcheck", category: "development", name: "ShellCheck", tagline: "Shell script analyzer", description: "Static analysis tool for shell scripts.", website: "https://www.shellcheck.net", license: "GPL-3.0", platforms: ["windows", "macos", "linux"], tags: ["linter", "shell", "bash"], alternatives_to: [], last_update: "2025-12-20", repo_url: "https://github.com/koalaman/shellcheck", is_foss: true, stars: 36500, maturity: "stable" },
    { id: "hadolint", category: "development", name: "Hadolint", tagline: "Dockerfile linter", description: "Dockerfile linter that helps you build best practice Docker images.", website: "https://github.com/hadolint/hadolint", license: "GPL-3.0", platforms: ["windows", "macos", "linux"], tags: ["linter", "docker", "best-practices"], alternatives_to: [], last_update: "2025-12-15", repo_url: "https://github.com/hadolint/hadolint", is_foss: true, stars: 10500, maturity: "stable" },
    { id: "yamllint", category: "development", name: "yamllint", tagline: "YAML linter", description: "Linter for YAML files.", website: "https://yamllint.readthedocs.io", license: "GPL-3.0", platforms: ["windows", "macos", "linux"], tags: ["linter", "yaml", "config"], alternatives_to: [], last_update: "2025-11-20", repo_url: "https://github.com/adrienverge/yamllint", is_foss: true, stars: 2800, maturity: "stable" },
    { id: "markdownlint", category: "development", name: "markdownlint", tagline: "Markdown linter", description: "Node.js style checker and lint tool for Markdown files.", website: "https://github.com/DavidAnson/markdownlint", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["linter", "markdown", "documentation"], alternatives_to: [], last_update: "2025-12-20", repo_url: "https://github.com/DavidAnson/markdownlint", is_foss: true, stars: 4800, maturity: "stable" },
    { id: "actionlint", category: "development", name: "actionlint", tagline: "GitHub Actions linter", description: "Static checker for GitHub Actions workflow files.", website: "https://github.com/rhysd/actionlint", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["linter", "github-actions", "ci"], alternatives_to: [], last_update: "2025-12-15", repo_url: "https://github.com/rhysd/actionlint", is_foss: true, stars: 2800, maturity: "stable" },
    { id: "oxlint", category: "development", name: "Oxlint", tagline: "Fast JavaScript linter", description: "Blazingly fast JavaScript linter written in Rust.", website: "https://oxc-project.github.io", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["linter", "javascript", "rust"], alternatives_to: ["ESLint"], last_update: "2026-01-10", repo_url: "https://github.com/oxc-project/oxc", is_foss: true, stars: 12000, maturity: "growing" },
    { id: "dprint", category: "development", name: "dprint", tagline: "Pluggable formatter", description: "Pluggable and configurable code formatting platform.", website: "https://dprint.dev", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["formatter", "pluggable", "fast"], alternatives_to: ["Prettier"], last_update: "2025-12-20", repo_url: "https://github.com/dprint/dprint", is_foss: true, stars: 3200, maturity: "stable" },

    // ==================== MORE DOCUMENTATION TOOLS ====================
    { id: "sphinx", category: "cms", name: "Sphinx", tagline: "Documentation generator", description: "Tool that makes it easy to create intelligent documentation.", website: "https://www.sphinx-doc.org", license: "BSD-2-Clause", platforms: ["windows", "macos", "linux"], tags: ["documentation", "python", "rst"], alternatives_to: ["MkDocs"], last_update: "2025-12-15", repo_url: "https://github.com/sphinx-doc/sphinx", is_foss: true, stars: 6500, maturity: "mature" },
    { id: "readthedocs", category: "cms", name: "Read the Docs", tagline: "Documentation hosting", description: "Documentation hosting platform for open source projects.", website: "https://readthedocs.org", license: "MIT", platforms: ["web"], tags: ["documentation", "hosting", "open-source"], alternatives_to: ["GitBook"], last_update: "2025-12-20", repo_url: "https://github.com/readthedocs/readthedocs.org", is_foss: true, stars: 8000, maturity: "stable" },
    { id: "gitbook", category: "cms", name: "GitBook", tagline: "Documentation platform", description: "Modern documentation platform for teams.", website: "https://www.gitbook.com", license: "Proprietary", platforms: ["web"], tags: ["documentation", "collaboration", "knowledge-base"], alternatives_to: ["Notion", "Confluence"], last_update: "2025-12-15", is_foss: false, maturity: "stable" },
    { id: "mintlify", category: "cms", name: "Mintlify", tagline: "Beautiful documentation", description: "Beautiful documentation that converts users.", website: "https://mintlify.com", license: "Proprietary", platforms: ["web"], tags: ["documentation", "api", "beautiful"], alternatives_to: ["GitBook"], last_update: "2025-12-20", is_foss: false, maturity: "growing" },
    { id: "nextra", category: "cms", name: "Nextra", tagline: "Next.js documentation", description: "Simple, powerful and flexible site generation framework.", website: "https://nextra.site", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["documentation", "nextjs", "mdx"], alternatives_to: ["Docusaurus"], last_update: "2025-12-15", repo_url: "https://github.com/shuding/nextra", is_foss: true, stars: 11500, maturity: "stable" },
    { id: "storybook", category: "development", name: "Storybook", tagline: "UI component explorer", description: "Frontend workshop for building UI components and pages in isolation.", website: "https://storybook.js.org", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["ui", "components", "documentation"], alternatives_to: [], last_update: "2026-01-10", repo_url: "https://github.com/storybookjs/storybook", is_foss: true, stars: 84000, maturity: "stable" },
    { id: "swagger", category: "api", name: "Swagger UI", tagline: "API documentation", description: "Visualize and interact with API resources.", website: "https://swagger.io", license: "Apache-2.0", platforms: ["web"], tags: ["api", "documentation", "openapi"], alternatives_to: ["Redoc"], last_update: "2025-12-20", repo_url: "https://github.com/swagger-api/swagger-ui", is_foss: true, stars: 26500, maturity: "stable" },
    { id: "redoc", category: "api", name: "Redoc", tagline: "OpenAPI documentation", description: "OpenAPI/Swagger-generated API reference documentation.", website: "https://redocly.com/redoc", license: "MIT", platforms: ["web"], tags: ["api", "documentation", "openapi"], alternatives_to: ["Swagger UI"], last_update: "2025-12-15", repo_url: "https://github.com/Redocly/redoc", is_foss: true, stars: 23500, maturity: "stable" },
    { id: "stoplight", category: "api", name: "Stoplight", tagline: "API design platform", description: "API design, documentation, and development platform.", website: "https://stoplight.io", license: "Proprietary", platforms: ["web"], tags: ["api", "design", "documentation"], alternatives_to: ["Swagger"], last_update: "2025-12-20", is_foss: false, maturity: "stable" },
    { id: "rapidoc", category: "api", name: "RapiDoc", tagline: "API documentation", description: "Custom element for OpenAPI spec viewing.", website: "https://rapidocweb.com", license: "MIT", platforms: ["web"], tags: ["api", "documentation", "web-component"], alternatives_to: ["Swagger UI"], last_update: "2025-11-20", repo_url: "https://github.com/rapi-doc/RapiDoc", is_foss: true, stars: 1700, maturity: "stable" },

];

module.exports = { finalTools };
