/**
 * Additional tools batch 2 - expanding to 1000+
 */

const moreTools = [
    // ==================== MORE NETWORKING TOOLS ====================
    { id: "openwrt", category: "networking", name: "OpenWrt", tagline: "Router firmware", description: "Linux operating system targeting embedded devices, primarily routers.", website: "https://openwrt.org", license: "GPL-2.0", platforms: ["linux"], tags: ["router", "firmware", "embedded"], alternatives_to: ["DD-WRT"], last_update: "2025-12-20", repo_url: "https://github.com/openwrt/openwrt", is_foss: true, stars: 20000, maturity: "mature" },
    { id: "pfsense", category: "networking", name: "pfSense", tagline: "Firewall/router", description: "Free network firewall distribution based on FreeBSD.", website: "https://www.pfsense.org", license: "Apache-2.0", platforms: ["linux"], tags: ["firewall", "router", "vpn"], alternatives_to: ["OPNsense"], last_update: "2025-12-15", repo_url: "https://github.com/pfsense/pfsense", is_foss: true, stars: 5000, maturity: "mature" },
    { id: "opnsense", category: "networking", name: "OPNsense", tagline: "Firewall platform", description: "Open source, easy-to-use firewall and routing platform.", website: "https://opnsense.org", license: "BSD-2-Clause", platforms: ["linux"], tags: ["firewall", "router", "security"], alternatives_to: ["pfSense"], last_update: "2025-12-20", repo_url: "https://github.com/opnsense/core", is_foss: true, stars: 3200, maturity: "stable" },
    { id: "zerotier", category: "networking", name: "ZeroTier", tagline: "Virtual networking", description: "Smart programmable Ethernet switch for planet Earth.", website: "https://www.zerotier.com", license: "BSL-1.1", platforms: ["windows", "macos", "linux", "ios", "android"], tags: ["vpn", "networking", "p2p"], alternatives_to: ["Tailscale"], last_update: "2025-12-15", repo_url: "https://github.com/zerotier/ZeroTierOne", is_foss: true, stars: 14000, maturity: "stable" },
    { id: "tailscale", category: "networking", name: "Tailscale", tagline: "Zero config VPN", description: "Zero config VPN that works on any platform.", website: "https://tailscale.com", license: "BSD-3-Clause", platforms: ["windows", "macos", "linux", "ios", "android"], tags: ["vpn", "wireguard", "mesh"], alternatives_to: ["ZeroTier"], last_update: "2026-01-10", repo_url: "https://github.com/tailscale/tailscale", is_foss: true, stars: 19000, maturity: "stable" },
    { id: "headscale", category: "networking", name: "Headscale", tagline: "Self-hosted Tailscale", description: "Open source, self-hosted implementation of Tailscale control server.", website: "https://github.com/juanfont/headscale", license: "BSD-3-Clause", platforms: ["linux"], tags: ["vpn", "tailscale", "self-hosted"], alternatives_to: ["Tailscale"], last_update: "2025-12-20", repo_url: "https://github.com/juanfont/headscale", is_foss: true, stars: 23000, maturity: "stable" },
    { id: "wireguard", category: "networking", name: "WireGuard", tagline: "Modern VPN", description: "Extremely simple yet fast and modern VPN.", website: "https://www.wireguard.com", license: "GPL-2.0", platforms: ["windows", "macos", "linux", "ios", "android"], tags: ["vpn", "encryption", "fast"], alternatives_to: ["OpenVPN"], last_update: "2025-12-15", repo_url: "https://github.com/WireGuard", is_foss: true, stars: 15000, maturity: "stable" },
    { id: "openvpn", category: "networking", name: "OpenVPN", tagline: "VPN solution", description: "Full-featured open source SSL VPN solution.", website: "https://openvpn.net", license: "GPL-2.0", platforms: ["windows", "macos", "linux"], tags: ["vpn", "ssl", "security"], alternatives_to: ["WireGuard"], last_update: "2025-12-20", repo_url: "https://github.com/OpenVPN/openvpn", is_foss: true, stars: 10500, maturity: "mature" },
    { id: "netbird", category: "networking", name: "NetBird", tagline: "WireGuard-based VPN", description: "Connect your devices into a single secure private WireGuard-based mesh network.", website: "https://netbird.io", license: "BSD-3-Clause", platforms: ["windows", "macos", "linux"], tags: ["vpn", "wireguard", "mesh"], alternatives_to: ["Tailscale"], last_update: "2026-01-05", repo_url: "https://github.com/netbirdio/netbird", is_foss: true, stars: 11000, maturity: "growing" },
    { id: "ntopng", category: "networking", name: "ntopng", tagline: "Network traffic monitor", description: "Web-based network traffic monitoring application.", website: "https://www.ntop.org/products/traffic-analysis/ntop", license: "GPL-3.0", platforms: ["linux"], tags: ["monitoring", "traffic", "analysis"], alternatives_to: [], last_update: "2025-12-15", repo_url: "https://github.com/ntop/ntopng", is_foss: true, stars: 6200, maturity: "stable" },
    { id: "snort", category: "networking", name: "Snort", tagline: "Network intrusion detection", description: "Network intrusion detection and prevention system.", website: "https://www.snort.org", license: "GPL-2.0", platforms: ["linux"], tags: ["ids", "ips", "security"], alternatives_to: ["Suricata"], last_update: "2025-12-20", repo_url: "https://github.com/snort3/snort3", is_foss: true, stars: 2000, maturity: "mature" },
    { id: "suricata", category: "networking", name: "Suricata", tagline: "Network security monitoring", description: "High performance network IDS, IPS and network security monitoring engine.", website: "https://suricata.io", license: "GPL-2.0", platforms: ["linux"], tags: ["ids", "ips", "monitoring"], alternatives_to: ["Snort"], last_update: "2025-12-15", repo_url: "https://github.com/OISF/suricata", is_foss: true, stars: 5000, maturity: "stable" },
    { id: "mitmproxy", category: "networking", name: "mitmproxy", tagline: "HTTP proxy", description: "Interactive HTTPS proxy for penetration testers and developers.", website: "https://mitmproxy.org", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["proxy", "https", "debugging"], alternatives_to: ["Charles Proxy"], last_update: "2025-12-20", repo_url: "https://github.com/mitmproxy/mitmproxy", is_foss: true, stars: 36500, maturity: "stable" },
    { id: "charles", category: "networking", name: "Charles Proxy", tagline: "HTTP debugging proxy", description: "HTTP proxy / HTTP monitor / Reverse Proxy for debugging.", website: "https://www.charlesproxy.com", license: "Proprietary", platforms: ["windows", "macos", "linux"], tags: ["proxy", "debugging", "http"], alternatives_to: ["mitmproxy"], last_update: "2025-12-15", is_foss: false, maturity: "stable" },
    { id: "proxyman", category: "networking", name: "Proxyman", tagline: "HTTP debugging proxy", description: "Modern and intuitive HTTP debugging proxy for macOS.", website: "https://proxyman.io", license: "Proprietary", platforms: ["macos", "ios"], tags: ["proxy", "debugging", "native"], alternatives_to: ["Charles Proxy"], last_update: "2025-12-20", is_foss: false, maturity: "stable" },


    // ==================== MORE CRM & BUSINESS ====================
    { id: "odoo", category: "crm", name: "Odoo", tagline: "Business apps suite", description: "Suite of open-source business apps covering CRM, e-commerce, accounting, and more.", website: "https://www.odoo.com", license: "LGPL-3.0", platforms: ["web", "self-hosted"], tags: ["erp", "crm", "business"], alternatives_to: ["Salesforce", "SAP"], last_update: "2026-01-10", repo_url: "https://github.com/odoo/odoo", is_foss: true, stars: 38000, maturity: "mature" },
    { id: "erpnext", category: "crm", name: "ERPNext", tagline: "Open source ERP", description: "Free and open-source integrated ERP software.", website: "https://erpnext.com", license: "GPL-3.0", platforms: ["web", "self-hosted"], tags: ["erp", "accounting", "inventory"], alternatives_to: ["SAP", "Oracle"], last_update: "2025-12-20", repo_url: "https://github.com/frappe/erpnext", is_foss: true, stars: 18500, maturity: "stable" },
    { id: "suitecrm", category: "crm", name: "SuiteCRM", tagline: "Open source CRM", description: "Award-winning open-source CRM software.", website: "https://suitecrm.com", license: "AGPL-3.0", platforms: ["web", "self-hosted"], tags: ["crm", "sales", "marketing"], alternatives_to: ["Salesforce", "HubSpot"], last_update: "2025-12-15", repo_url: "https://github.com/salesagility/SuiteCRM", is_foss: true, stars: 4500, maturity: "stable" },
    { id: "espocrm", category: "crm", name: "EspoCRM", tagline: "Web CRM application", description: "Open source CRM application with clean interface.", website: "https://www.espocrm.com", license: "GPL-3.0", platforms: ["web", "self-hosted"], tags: ["crm", "sales", "contacts"], alternatives_to: ["Salesforce"], last_update: "2025-12-20", repo_url: "https://github.com/espocrm/espocrm", is_foss: true, stars: 1700, maturity: "stable" },
    { id: "twenty", category: "crm", name: "Twenty", tagline: "Modern CRM", description: "Modern, open-source CRM alternative to Salesforce.", website: "https://twenty.com", license: "AGPL-3.0", platforms: ["web", "self-hosted"], tags: ["crm", "modern", "salesforce-alternative"], alternatives_to: ["Salesforce"], last_update: "2026-01-08", repo_url: "https://github.com/twentyhq/twenty", is_foss: true, stars: 18000, maturity: "growing" },
    { id: "dolibarr", category: "crm", name: "Dolibarr", tagline: "ERP & CRM", description: "Modern software package to manage your company or foundation.", website: "https://www.dolibarr.org", license: "GPL-3.0", platforms: ["web", "self-hosted"], tags: ["erp", "crm", "invoicing"], alternatives_to: ["Odoo"], last_update: "2025-12-15", repo_url: "https://github.com/Dolibarr/dolibarr", is_foss: true, stars: 5500, maturity: "stable" },
    { id: "akaunting", category: "finance", name: "Akaunting", tagline: "Accounting software", description: "Free, open-source, and online accounting software.", website: "https://akaunting.com", license: "GPL-3.0", platforms: ["web", "self-hosted"], tags: ["accounting", "invoicing", "expenses"], alternatives_to: ["QuickBooks", "Xero"], last_update: "2025-12-20", repo_url: "https://github.com/akaunting/akaunting", is_foss: true, stars: 8000, maturity: "stable" },
    { id: "manager", category: "finance", name: "Manager", tagline: "Accounting software", description: "Free accounting software for small business.", website: "https://www.manager.io", license: "Proprietary", platforms: ["windows", "macos", "linux"], tags: ["accounting", "small-business", "free"], alternatives_to: ["QuickBooks"], last_update: "2025-12-15", is_foss: false, maturity: "stable" },
    { id: "kimai", category: "project", name: "Kimai", tagline: "Time tracking", description: "Free & open source time tracking software.", website: "https://www.kimai.org", license: "MIT", platforms: ["web", "self-hosted"], tags: ["time-tracking", "invoicing", "projects"], alternatives_to: ["Toggl", "Harvest"], last_update: "2025-12-20", repo_url: "https://github.com/kimai/kimai", is_foss: true, stars: 3200, maturity: "stable" },
    { id: "clockify", category: "project", name: "Clockify", tagline: "Time tracker", description: "Free time tracking software for teams.", website: "https://clockify.me", license: "Proprietary", platforms: ["windows", "macos", "linux", "web", "ios", "android"], tags: ["time-tracking", "teams", "free"], alternatives_to: ["Toggl"], last_update: "2025-12-15", is_foss: false, maturity: "stable" },
    { id: "traggo", category: "project", name: "Traggo", tagline: "Tag-based time tracking", description: "Tag-based time tracking tool.", website: "https://traggo.net", license: "GPL-3.0", platforms: ["web", "self-hosted"], tags: ["time-tracking", "tags", "self-hosted"], alternatives_to: ["Toggl"], last_update: "2025-11-20", repo_url: "https://github.com/traggo/server", is_foss: true, stars: 1200, maturity: "stable" },

    // ==================== MORE SCIENCE & RESEARCH ====================
    { id: "scipy", category: "science", name: "SciPy", tagline: "Scientific computing", description: "Open-source software for mathematics, science, and engineering.", website: "https://scipy.org", license: "BSD-3-Clause", platforms: ["windows", "macos", "linux"], tags: ["python", "scientific", "numerical"], alternatives_to: ["MATLAB"], last_update: "2025-12-20", repo_url: "https://github.com/scipy/scipy", is_foss: true, stars: 13000, maturity: "mature" },
    { id: "numpy", category: "science", name: "NumPy", tagline: "Numerical computing", description: "Fundamental package for scientific computing with Python.", website: "https://numpy.org", license: "BSD-3-Clause", platforms: ["windows", "macos", "linux"], tags: ["python", "arrays", "numerical"], alternatives_to: [], last_update: "2025-12-15", repo_url: "https://github.com/numpy/numpy", is_foss: true, stars: 27500, maturity: "mature" },
    { id: "pandas", category: "science", name: "pandas", tagline: "Data analysis library", description: "Powerful data structures for data analysis and manipulation.", website: "https://pandas.pydata.org", license: "BSD-3-Clause", platforms: ["windows", "macos", "linux"], tags: ["python", "data-analysis", "dataframes"], alternatives_to: [], last_update: "2025-12-20", repo_url: "https://github.com/pandas-dev/pandas", is_foss: true, stars: 43500, maturity: "mature" },
    { id: "matplotlib", category: "science", name: "Matplotlib", tagline: "Plotting library", description: "Comprehensive library for creating static, animated, and interactive visualizations.", website: "https://matplotlib.org", license: "PSF", platforms: ["windows", "macos", "linux"], tags: ["python", "plotting", "visualization"], alternatives_to: [], last_update: "2025-12-15", repo_url: "https://github.com/matplotlib/matplotlib", is_foss: true, stars: 20000, maturity: "mature" },
    { id: "seaborn", category: "science", name: "Seaborn", tagline: "Statistical visualization", description: "Statistical data visualization library based on matplotlib.", website: "https://seaborn.pydata.org", license: "BSD-3-Clause", platforms: ["windows", "macos", "linux"], tags: ["python", "statistics", "visualization"], alternatives_to: [], last_update: "2025-12-20", repo_url: "https://github.com/mwaskom/seaborn", is_foss: true, stars: 12500, maturity: "stable" },
    { id: "plotly", category: "science", name: "Plotly", tagline: "Interactive graphing", description: "Interactive graphing library for Python.", website: "https://plotly.com/python", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["python", "interactive", "visualization"], alternatives_to: ["Matplotlib"], last_update: "2025-12-15", repo_url: "https://github.com/plotly/plotly.py", is_foss: true, stars: 16000, maturity: "stable" },
    { id: "bokeh", category: "science", name: "Bokeh", tagline: "Interactive visualization", description: "Interactive visualization library for modern web browsers.", website: "https://bokeh.org", license: "BSD-3-Clause", platforms: ["windows", "macos", "linux"], tags: ["python", "interactive", "web"], alternatives_to: ["Plotly"], last_update: "2025-12-20", repo_url: "https://github.com/bokeh/bokeh", is_foss: true, stars: 19500, maturity: "stable" },
    { id: "scikit-learn", category: "science", name: "scikit-learn", tagline: "Machine learning in Python", description: "Simple and efficient tools for predictive data analysis.", website: "https://scikit-learn.org", license: "BSD-3-Clause", platforms: ["windows", "macos", "linux"], tags: ["python", "ml", "classification"], alternatives_to: [], last_update: "2025-12-15", repo_url: "https://github.com/scikit-learn/scikit-learn", is_foss: true, stars: 60000, maturity: "mature" },
    { id: "keras", category: "science", name: "Keras", tagline: "Deep learning API", description: "Deep learning API written in Python, running on top of TensorFlow.", website: "https://keras.io", license: "Apache-2.0", platforms: ["windows", "macos", "linux"], tags: ["python", "deep-learning", "neural-networks"], alternatives_to: [], last_update: "2025-12-20", repo_url: "https://github.com/keras-team/keras", is_foss: true, stars: 62000, maturity: "mature" },
    { id: "opencv", category: "science", name: "OpenCV", tagline: "Computer vision library", description: "Open source computer vision and machine learning software library.", website: "https://opencv.org", license: "Apache-2.0", platforms: ["windows", "macos", "linux"], tags: ["computer-vision", "image-processing", "ml"], alternatives_to: [], last_update: "2025-12-15", repo_url: "https://github.com/opencv/opencv", is_foss: true, stars: 79000, maturity: "mature" },
    { id: "spacy", category: "science", name: "spaCy", tagline: "NLP library", description: "Industrial-strength Natural Language Processing in Python.", website: "https://spacy.io", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["nlp", "python", "text-processing"], alternatives_to: ["NLTK"], last_update: "2025-12-20", repo_url: "https://github.com/explosion/spaCy", is_foss: true, stars: 30000, maturity: "stable" },
    { id: "nltk", category: "science", name: "NLTK", tagline: "Natural language toolkit", description: "Platform for building Python programs to work with human language data.", website: "https://www.nltk.org", license: "Apache-2.0", platforms: ["windows", "macos", "linux"], tags: ["nlp", "python", "linguistics"], alternatives_to: ["spaCy"], last_update: "2025-12-15", repo_url: "https://github.com/nltk/nltk", is_foss: true, stars: 13500, maturity: "mature" },
    { id: "r-project", category: "science", name: "R", tagline: "Statistical computing", description: "Language and environment for statistical computing and graphics.", website: "https://www.r-project.org", license: "GPL-2.0", platforms: ["windows", "macos", "linux"], tags: ["statistics", "data-analysis", "visualization"], alternatives_to: ["Python"], last_update: "2025-12-20", repo_url: "https://github.com/wch/r-source", is_foss: true, stars: 1000, maturity: "mature" },
    { id: "gnuplot", category: "science", name: "Gnuplot", tagline: "Plotting program", description: "Portable command-line driven graphing utility.", website: "http://www.gnuplot.info", license: "gnuplot", platforms: ["windows", "macos", "linux"], tags: ["plotting", "graphs", "cli"], alternatives_to: ["Matplotlib"], last_update: "2025-11-20", repo_url: "https://sourceforge.net/projects/gnuplot", is_foss: true, stars: 500, maturity: "mature" },
    { id: "paraview", category: "science", name: "ParaView", tagline: "Scientific visualization", description: "Open-source, multi-platform data analysis and visualization application.", website: "https://www.paraview.org", license: "BSD-3-Clause", platforms: ["windows", "macos", "linux"], tags: ["visualization", "3d", "scientific"], alternatives_to: [], last_update: "2025-12-15", repo_url: "https://github.com/Kitware/ParaView", is_foss: true, stars: 2500, maturity: "stable" },
    { id: "vtk", category: "science", name: "VTK", tagline: "Visualization toolkit", description: "Open-source software for 3D computer graphics and visualization.", website: "https://vtk.org", license: "BSD-3-Clause", platforms: ["windows", "macos", "linux"], tags: ["3d", "visualization", "graphics"], alternatives_to: [], last_update: "2025-12-20", repo_url: "https://github.com/Kitware/VTK", is_foss: true, stars: 2800, maturity: "mature" },


    // ==================== MORE PHOTOGRAPHY ====================
    { id: "photogimpgimp", category: "photography", name: "PhotoGIMP", tagline: "GIMP for photographers", description: "GIMP patch that provides Photoshop-like experience.", website: "https://github.com/Diolinux/PhotoGIMP", license: "GPL-3.0", platforms: ["windows", "macos", "linux"], tags: ["photo-editing", "gimp", "photoshop-like"], alternatives_to: ["Photoshop"], last_update: "2025-10-15", repo_url: "https://github.com/Diolinux/PhotoGIMP", is_foss: true, stars: 14000, maturity: "stable" },
    { id: "hugin", category: "photography", name: "Hugin", tagline: "Panorama photo stitcher", description: "Cross-platform panorama photo stitching and HDR merging program.", website: "https://hugin.sourceforge.io", license: "GPL-2.0", platforms: ["windows", "macos", "linux"], tags: ["panorama", "stitching", "hdr"], alternatives_to: ["PTGui"], last_update: "2025-11-20", repo_url: "https://sourceforge.net/projects/hugin", is_foss: true, stars: 500, maturity: "stable" },
    { id: "luminance-hdr", category: "photography", name: "Luminance HDR", tagline: "HDR imaging", description: "Complete workflow for HDR imaging.", website: "http://qtpfsgui.sourceforge.net", license: "GPL-2.0", platforms: ["windows", "macos", "linux"], tags: ["hdr", "tone-mapping", "photography"], alternatives_to: ["Photomatix"], last_update: "2025-09-15", repo_url: "https://github.com/LuminanceHDR/LuminanceHDR", is_foss: true, stars: 500, maturity: "stable" },
    { id: "rapid-photo-downloader", category: "photography", name: "Rapid Photo Downloader", tagline: "Photo import tool", description: "Photo and video downloader for Linux.", website: "https://damonlynch.net/rapid", license: "GPL-3.0", platforms: ["linux"], tags: ["import", "photos", "organization"], alternatives_to: [], last_update: "2025-10-20", repo_url: "https://github.com/damonlynch/rapid-photo-downloader", is_foss: true, stars: 300, maturity: "stable" },
    { id: "shotwell", category: "photography", name: "Shotwell", tagline: "Photo manager", description: "Personal photo manager for GNOME.", website: "https://wiki.gnome.org/Apps/Shotwell", license: "LGPL-2.1", platforms: ["linux"], tags: ["photos", "organization", "gnome"], alternatives_to: ["Google Photos"], last_update: "2025-12-15", repo_url: "https://gitlab.gnome.org/GNOME/shotwell", is_foss: true, stars: 500, maturity: "stable" },
    { id: "gthumb", category: "photography", name: "gThumb", tagline: "Image viewer", description: "Image viewer and browser for GNOME.", website: "https://wiki.gnome.org/Apps/Gthumb", license: "GPL-2.0", platforms: ["linux"], tags: ["viewer", "browser", "gnome"], alternatives_to: [], last_update: "2025-11-20", repo_url: "https://gitlab.gnome.org/GNOME/gthumb", is_foss: true, stars: 200, maturity: "stable" },
    { id: "nomacs", category: "photography", name: "nomacs", tagline: "Image viewer", description: "Free, open source image viewer with editing capabilities.", website: "https://nomacs.org", license: "GPL-3.0", platforms: ["windows", "macos", "linux"], tags: ["viewer", "editing", "lightweight"], alternatives_to: ["IrfanView"], last_update: "2025-12-10", repo_url: "https://github.com/nomacs/nomacs", is_foss: true, stars: 2000, maturity: "stable" },
    { id: "xnview", category: "photography", name: "XnView MP", tagline: "Image viewer", description: "Powerful cross-platform media browser, viewer and converter.", website: "https://www.xnview.com", license: "Freeware", platforms: ["windows", "macos", "linux"], tags: ["viewer", "converter", "batch"], alternatives_to: ["IrfanView"], last_update: "2025-12-15", is_foss: false, maturity: "stable" },
    { id: "imagemagick", category: "photography", name: "ImageMagick", tagline: "Image manipulation", description: "Create, edit, compose, or convert digital images.", website: "https://imagemagick.org", license: "Apache-2.0", platforms: ["windows", "macos", "linux"], tags: ["cli", "conversion", "manipulation"], alternatives_to: [], last_update: "2025-12-20", repo_url: "https://github.com/ImageMagick/ImageMagick", is_foss: true, stars: 12000, maturity: "mature" },
    { id: "exiftool", category: "photography", name: "ExifTool", tagline: "Metadata editor", description: "Read, write and edit meta information in image files.", website: "https://exiftool.org", license: "Artistic-1.0", platforms: ["windows", "macos", "linux"], tags: ["metadata", "exif", "cli"], alternatives_to: [], last_update: "2025-12-15", repo_url: "https://github.com/exiftool/exiftool", is_foss: true, stars: 3000, maturity: "mature" },

    // ==================== MORE 3D & CAD ====================
    { id: "openscad", category: "3d", name: "OpenSCAD", tagline: "Programmable CAD", description: "The programmers solid 3D CAD modeller.", website: "https://openscad.org", license: "GPL-2.0", platforms: ["windows", "macos", "linux"], tags: ["cad", "3d", "programming"], alternatives_to: [], last_update: "2025-12-15", repo_url: "https://github.com/openscad/openscad", is_foss: true, stars: 7000, maturity: "stable" },
    { id: "meshlab", category: "3d", name: "MeshLab", tagline: "3D mesh processing", description: "Open source system for processing and editing 3D triangular meshes.", website: "https://www.meshlab.net", license: "GPL-3.0", platforms: ["windows", "macos", "linux"], tags: ["3d", "mesh", "processing"], alternatives_to: [], last_update: "2025-11-20", repo_url: "https://github.com/cnr-isti-vclab/meshlab", is_foss: true, stars: 4800, maturity: "stable" },
    { id: "meshroom", category: "3d", name: "Meshroom", tagline: "3D reconstruction", description: "Open-source 3D reconstruction software based on AliceVision.", website: "https://alicevision.org", license: "MPL-2.0", platforms: ["windows", "linux"], tags: ["3d", "photogrammetry", "reconstruction"], alternatives_to: ["RealityCapture"], last_update: "2025-12-10", repo_url: "https://github.com/alicevision/Meshroom", is_foss: true, stars: 11500, maturity: "stable" },
    { id: "dust3d", category: "3d", name: "Dust3D", tagline: "3D modeling for beginners", description: "Cross-platform 3D modeling software for quick creation.", website: "https://dust3d.org", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["3d", "modeling", "beginner"], alternatives_to: ["Blender"], last_update: "2025-09-15", repo_url: "https://github.com/huxingyi/dust3d", is_foss: true, stars: 3500, maturity: "stable" },
    { id: "wings3d", category: "3d", name: "Wings 3D", tagline: "Subdivision modeler", description: "Advanced subdivision modeler inspired by Nendo and Mirai.", website: "http://www.wings3d.com", license: "BSD-3-Clause", platforms: ["windows", "macos", "linux"], tags: ["3d", "modeling", "subdivision"], alternatives_to: ["Blender"], last_update: "2025-10-20", repo_url: "https://github.com/dgud/wings", is_foss: true, stars: 700, maturity: "stable" },
    { id: "solvespace", category: "3d", name: "SolveSpace", tagline: "Parametric CAD", description: "Parametric 2D/3D CAD with constraint solver.", website: "https://solvespace.com", license: "GPL-3.0", platforms: ["windows", "macos", "linux"], tags: ["cad", "parametric", "constraints"], alternatives_to: ["FreeCAD"], last_update: "2025-11-15", repo_url: "https://github.com/solvespace/solvespace", is_foss: true, stars: 3200, maturity: "stable" },
    { id: "brlcad", category: "3d", name: "BRL-CAD", tagline: "Solid modeling CAD", description: "Powerful cross-platform solid modeling system.", website: "https://brlcad.org", license: "LGPL-2.1", platforms: ["windows", "macos", "linux"], tags: ["cad", "solid-modeling", "analysis"], alternatives_to: [], last_update: "2025-10-15", repo_url: "https://github.com/BRL-CAD/brlcad", is_foss: true, stars: 500, maturity: "stable" },
    { id: "cura", category: "3d", name: "Ultimaker Cura", tagline: "3D printing slicer", description: "Powerful, easy-to-use 3D printing slicer software.", website: "https://ultimaker.com/software/ultimaker-cura", license: "LGPL-3.0", platforms: ["windows", "macos", "linux"], tags: ["3d-printing", "slicer", "gcode"], alternatives_to: ["PrusaSlicer"], last_update: "2025-12-20", repo_url: "https://github.com/Ultimaker/Cura", is_foss: true, stars: 6500, maturity: "stable" },
    { id: "prusaslicer", category: "3d", name: "PrusaSlicer", tagline: "3D printing slicer", description: "Feature-rich, frequently updated slicer for 3D printers.", website: "https://www.prusa3d.com/prusaslicer", license: "AGPL-3.0", platforms: ["windows", "macos", "linux"], tags: ["3d-printing", "slicer", "prusa"], alternatives_to: ["Cura"], last_update: "2025-12-15", repo_url: "https://github.com/prusa3d/PrusaSlicer", is_foss: true, stars: 8000, maturity: "stable" },
    { id: "orcaslicer", category: "3d", name: "OrcaSlicer", tagline: "3D printing slicer", description: "G-code generator for 3D printers, fork of Bambu Studio.", website: "https://github.com/SoftFever/OrcaSlicer", license: "AGPL-3.0", platforms: ["windows", "macos", "linux"], tags: ["3d-printing", "slicer", "bambu"], alternatives_to: ["PrusaSlicer"], last_update: "2026-01-10", repo_url: "https://github.com/SoftFever/OrcaSlicer", is_foss: true, stars: 7500, maturity: "growing" },


    // ==================== MORE UTILITIES ====================
    { id: "flameshot", category: "file", name: "Flameshot", tagline: "Screenshot tool", description: "Powerful yet simple to use screenshot software.", website: "https://flameshot.org", license: "GPL-3.0", platforms: ["windows", "macos", "linux"], tags: ["screenshot", "annotation", "capture"], alternatives_to: ["Snagit", "Greenshot"], last_update: "2025-12-15", repo_url: "https://github.com/flameshot-org/flameshot", is_foss: true, stars: 24500, maturity: "stable" },
    { id: "sharex", category: "file", name: "ShareX", tagline: "Screen capture", description: "Free and open source program for screen capture and file sharing.", website: "https://getsharex.com", license: "GPL-3.0", platforms: ["windows"], tags: ["screenshot", "recording", "sharing"], alternatives_to: ["Snagit"], last_update: "2025-12-20", repo_url: "https://github.com/ShareX/ShareX", is_foss: true, stars: 30000, maturity: "stable" },
    { id: "greenshot", category: "file", name: "Greenshot", tagline: "Screenshot tool", description: "Light-weight screenshot software tool for Windows.", website: "https://getgreenshot.org", license: "GPL-3.0", platforms: ["windows"], tags: ["screenshot", "annotation", "lightweight"], alternatives_to: ["Snagit"], last_update: "2025-11-20", repo_url: "https://github.com/greenshot/greenshot", is_foss: true, stars: 4000, maturity: "stable" },
    { id: "ksnip", category: "file", name: "ksnip", tagline: "Screenshot tool", description: "Cross-platform screenshot and annotation tool.", website: "https://github.com/ksnip/ksnip", license: "GPL-2.0", platforms: ["windows", "macos", "linux"], tags: ["screenshot", "annotation", "cross-platform"], alternatives_to: ["Flameshot"], last_update: "2025-12-10", repo_url: "https://github.com/ksnip/ksnip", is_foss: true, stars: 2000, maturity: "stable" },
    { id: "peek", category: "file", name: "Peek", tagline: "GIF recorder", description: "Simple animated GIF screen recorder with an easy to use interface.", website: "https://github.com/phw/peek", license: "GPL-3.0", platforms: ["linux"], tags: ["gif", "recording", "screen-capture"], alternatives_to: ["LICEcap"], last_update: "2025-09-15", repo_url: "https://github.com/phw/peek", is_foss: true, stars: 10500, maturity: "stable" },
    { id: "gifski", category: "file", name: "Gifski", tagline: "GIF encoder", description: "Highest-quality GIF encoder based on pngquant.", website: "https://gif.ski", license: "AGPL-3.0", platforms: ["windows", "macos", "linux"], tags: ["gif", "encoder", "quality"], alternatives_to: [], last_update: "2025-12-15", repo_url: "https://github.com/ImageOptim/gifski", is_foss: true, stars: 3500, maturity: "stable" },
    { id: "barrier", category: "file", name: "Barrier", tagline: "KVM software", description: "Open-source KVM software to share mouse and keyboard.", website: "https://github.com/debauchee/barrier", license: "GPL-2.0", platforms: ["windows", "macos", "linux"], tags: ["kvm", "mouse", "keyboard"], alternatives_to: ["Synergy"], last_update: "2025-10-20", repo_url: "https://github.com/debauchee/barrier", is_foss: true, stars: 14500, maturity: "stable" },
    { id: "input-leap", category: "file", name: "Input Leap", tagline: "KVM software", description: "Open-source KVM software, fork of Barrier.", website: "https://github.com/input-leap/input-leap", license: "GPL-2.0", platforms: ["windows", "macos", "linux"], tags: ["kvm", "mouse", "keyboard"], alternatives_to: ["Barrier", "Synergy"], last_update: "2025-12-20", repo_url: "https://github.com/input-leap/input-leap", is_foss: true, stars: 3000, maturity: "growing" },
    { id: "deskreen", category: "file", name: "Deskreen", tagline: "Screen sharing", description: "Turn any device with a web browser into a secondary screen.", website: "https://deskreen.com", license: "AGPL-3.0", platforms: ["windows", "macos", "linux"], tags: ["screen-sharing", "second-screen", "webrtc"], alternatives_to: [], last_update: "2025-11-15", repo_url: "https://github.com/nicotine-plus/nicotine-plus", is_foss: true, stars: 16000, maturity: "stable" },
    { id: "rustdesk", category: "file", name: "RustDesk", tagline: "Remote desktop", description: "Open-source remote desktop software, written in Rust.", website: "https://rustdesk.com", license: "AGPL-3.0", platforms: ["windows", "macos", "linux", "ios", "android"], tags: ["remote-desktop", "self-hosted", "rust"], alternatives_to: ["TeamViewer", "AnyDesk"], last_update: "2026-01-10", repo_url: "https://github.com/rustdesk/rustdesk", is_foss: true, stars: 75000, maturity: "stable" },
    { id: "parsec", category: "file", name: "Parsec", tagline: "Remote desktop for gaming", description: "Low-latency remote desktop for gaming and work.", website: "https://parsec.app", license: "Proprietary", platforms: ["windows", "macos", "linux", "android"], tags: ["remote-desktop", "gaming", "low-latency"], alternatives_to: ["Steam Remote Play"], last_update: "2025-12-15", is_foss: false, maturity: "stable" },
    { id: "sunshine", category: "file", name: "Sunshine", tagline: "Game streaming host", description: "Self-hosted game stream host for Moonlight.", website: "https://github.com/LizardByte/Sunshine", license: "GPL-3.0", platforms: ["windows", "macos", "linux"], tags: ["streaming", "gaming", "moonlight"], alternatives_to: ["NVIDIA GameStream"], last_update: "2026-01-08", repo_url: "https://github.com/LizardByte/Sunshine", is_foss: true, stars: 19000, maturity: "stable" },
    { id: "moonlight", category: "file", name: "Moonlight", tagline: "Game streaming client", description: "Open source implementation of NVIDIA's GameStream protocol.", website: "https://moonlight-stream.org", license: "GPL-3.0", platforms: ["windows", "macos", "linux", "ios", "android"], tags: ["streaming", "gaming", "client"], alternatives_to: [], last_update: "2025-12-20", repo_url: "https://github.com/moonlight-stream/moonlight-qt", is_foss: true, stars: 9000, maturity: "stable" },
    { id: "localsend", category: "file", name: "LocalSend", tagline: "Local file sharing", description: "Share files to nearby devices without internet.", website: "https://localsend.org", license: "MIT", platforms: ["windows", "macos", "linux", "ios", "android"], tags: ["file-sharing", "local", "airdrop-alternative"], alternatives_to: ["AirDrop"], last_update: "2026-01-05", repo_url: "https://github.com/localsend/localsend", is_foss: true, stars: 50000, maturity: "stable" },
    { id: "warpinator", category: "file", name: "Warpinator", tagline: "LAN file transfer", description: "Share files across the LAN.", website: "https://github.com/linuxmint/warpinator", license: "GPL-3.0", platforms: ["linux"], tags: ["file-sharing", "lan", "linux-mint"], alternatives_to: ["LocalSend"], last_update: "2025-12-15", repo_url: "https://github.com/linuxmint/warpinator", is_foss: true, stars: 1500, maturity: "stable" },
    { id: "qbittorrent", category: "file", name: "qBittorrent", tagline: "BitTorrent client", description: "Free and reliable P2P BitTorrent client.", website: "https://www.qbittorrent.org", license: "GPL-2.0", platforms: ["windows", "macos", "linux"], tags: ["torrent", "p2p", "download"], alternatives_to: ["uTorrent"], last_update: "2025-12-20", repo_url: "https://github.com/qbittorrent/qBittorrent", is_foss: true, stars: 28000, maturity: "stable" },
    { id: "transmission", category: "file", name: "Transmission", tagline: "BitTorrent client", description: "Fast, easy, and free BitTorrent client.", website: "https://transmissionbt.com", license: "GPL-2.0", platforms: ["windows", "macos", "linux"], tags: ["torrent", "lightweight", "p2p"], alternatives_to: ["qBittorrent"], last_update: "2025-12-15", repo_url: "https://github.com/transmission/transmission", is_foss: true, stars: 12500, maturity: "stable" },
    { id: "deluge", category: "file", name: "Deluge", tagline: "BitTorrent client", description: "Lightweight, free software, cross-platform BitTorrent client.", website: "https://deluge-torrent.org", license: "GPL-3.0", platforms: ["windows", "macos", "linux"], tags: ["torrent", "plugins", "p2p"], alternatives_to: ["qBittorrent"], last_update: "2025-11-20", repo_url: "https://github.com/deluge-torrent/deluge", is_foss: true, stars: 1500, maturity: "stable" },
    { id: "aria2", category: "file", name: "aria2", tagline: "Download utility", description: "Lightweight multi-protocol & multi-source download utility.", website: "https://aria2.github.io", license: "GPL-2.0", platforms: ["windows", "macos", "linux"], tags: ["download", "cli", "multi-protocol"], alternatives_to: ["wget"], last_update: "2025-10-15", repo_url: "https://github.com/aria2/aria2", is_foss: true, stars: 35500, maturity: "stable" },
    { id: "yt-dlp", category: "file", name: "yt-dlp", tagline: "Video downloader", description: "Feature-rich command-line audio/video downloader.", website: "https://github.com/yt-dlp/yt-dlp", license: "Unlicense", platforms: ["windows", "macos", "linux"], tags: ["download", "video", "youtube"], alternatives_to: ["youtube-dl"], last_update: "2026-01-12", repo_url: "https://github.com/yt-dlp/yt-dlp", is_foss: true, stars: 87000, maturity: "stable" },
    { id: "gallery-dl", category: "file", name: "gallery-dl", tagline: "Image downloader", description: "Command-line program to download image galleries.", website: "https://github.com/mikf/gallery-dl", license: "GPL-2.0", platforms: ["windows", "macos", "linux"], tags: ["download", "images", "galleries"], alternatives_to: [], last_update: "2025-12-20", repo_url: "https://github.com/mikf/gallery-dl", is_foss: true, stars: 12000, maturity: "stable" },

];

module.exports = { moreTools };
