/**
 * Ultimate tools batch - Final 150+ tools to exceed 1000
 */

const ultimateTools = [
    // ==================== COMMUNICATION EXTRAS ====================
    { id: "discord", category: "communication", name: "Discord", tagline: "Voice & text chat", description: "Voice, video and text communication platform.", website: "https://discord.com", license: "Proprietary", platforms: ["windows", "macos", "linux", "ios", "android", "web"], tags: ["chat", "voice", "gaming"], alternatives_to: ["Slack", "TeamSpeak"], last_update: "2026-01-15", is_foss: false, maturity: "mature" },
    { id: "revolt", category: "communication", name: "Revolt", tagline: "Discord alternative", description: "User-first chat platform built with modern web technologies.", website: "https://revolt.chat", license: "AGPL-3.0", platforms: ["windows", "macos", "linux", "web"], tags: ["chat", "discord-alternative", "open-source"], alternatives_to: ["Discord"], last_update: "2025-12-20", repo_url: "https://github.com/revoltchat/revolt", is_foss: true, stars: 3000, maturity: "growing" },
    { id: "guilded", category: "communication", name: "Guilded", tagline: "Team chat", description: "Chat platform for gaming communities with advanced features.", website: "https://www.guilded.gg", license: "Proprietary", platforms: ["windows", "macos", "linux", "ios", "android", "web"], tags: ["chat", "gaming", "teams"], alternatives_to: ["Discord"], last_update: "2025-12-15", is_foss: false, maturity: "stable" },
    { id: "mumble", category: "communication", name: "Mumble", tagline: "Voice chat", description: "Open-source, low-latency, high quality voice chat software.", website: "https://www.mumble.info", license: "BSD-3-Clause", platforms: ["windows", "macos", "linux", "ios", "android"], tags: ["voice", "gaming", "low-latency"], alternatives_to: ["TeamSpeak", "Discord"], last_update: "2025-11-20", repo_url: "https://github.com/mumble-voip/mumble", is_foss: true, stars: 6200, maturity: "stable" },
    { id: "jitsi", category: "communication", name: "Jitsi Meet", tagline: "Video conferencing", description: "Secure, fully featured, and completely free video conferencing.", website: "https://jitsi.org", license: "Apache-2.0", platforms: ["windows", "macos", "linux", "ios", "android", "web"], tags: ["video", "conferencing", "webrtc"], alternatives_to: ["Zoom", "Google Meet"], last_update: "2025-12-20", repo_url: "https://github.com/jitsi/jitsi-meet", is_foss: true, stars: 23000, maturity: "stable" },
    { id: "bigbluebutton", category: "communication", name: "BigBlueButton", tagline: "Web conferencing", description: "Open-source web conferencing system for online learning.", website: "https://bigbluebutton.org", license: "LGPL-3.0", platforms: ["web", "self-hosted"], tags: ["video", "education", "conferencing"], alternatives_to: ["Zoom"], last_update: "2025-12-15", repo_url: "https://github.com/bigbluebutton/bigbluebutton", is_foss: true, stars: 8500, maturity: "stable" },
    { id: "wire", category: "communication", name: "Wire", tagline: "Secure messenger", description: "Most secure collaboration platform with end-to-end encryption.", website: "https://wire.com", license: "GPL-3.0", platforms: ["windows", "macos", "linux", "ios", "android", "web"], tags: ["messaging", "encryption", "collaboration"], alternatives_to: ["Slack", "Teams"], last_update: "2025-12-20", repo_url: "https://github.com/wireapp/wire-webapp", is_foss: true, stars: 2800, maturity: "stable" },
    { id: "simplex", category: "communication", name: "SimpleX Chat", tagline: "Private messenger", description: "First messenger without user IDs for maximum privacy.", website: "https://simplex.chat", license: "AGPL-3.0", platforms: ["windows", "macos", "linux", "ios", "android"], tags: ["messaging", "privacy", "decentralized"], alternatives_to: ["Signal"], last_update: "2025-12-15", repo_url: "https://github.com/simplex-chat/simplex-chat", is_foss: true, stars: 6000, maturity: "growing" },

    // ==================== DEVELOPMENT EXTRAS ====================
    { id: "sublime-text", category: "development", name: "Sublime Text", tagline: "Text editor", description: "Sophisticated text editor for code, markup and prose.", website: "https://www.sublimetext.com", license: "Proprietary", platforms: ["windows", "macos", "linux"], tags: ["editor", "fast", "extensible"], alternatives_to: ["VS Code"], last_update: "2025-12-20", is_foss: false, maturity: "mature" },
    { id: "atom", category: "development", name: "Pulsar", tagline: "Hackable editor", description: "Community-led hyper-hackable text editor (Atom fork).", website: "https://pulsar-edit.dev", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["editor", "hackable", "electron"], alternatives_to: ["VS Code", "Atom"], last_update: "2025-12-15", repo_url: "https://github.com/pulsar-edit/pulsar", is_foss: true, stars: 3000, maturity: "stable" },
    { id: "kate", category: "development", name: "Kate", tagline: "Advanced text editor", description: "Advanced text editor for KDE with LSP support.", website: "https://kate-editor.org", license: "LGPL-2.0", platforms: ["windows", "macos", "linux"], tags: ["editor", "kde", "lsp"], alternatives_to: ["VS Code"], last_update: "2025-12-20", repo_url: "https://invent.kde.org/utilities/kate", is_foss: true, stars: 1800, maturity: "stable" },
    { id: "geany", category: "development", name: "Geany", tagline: "Lightweight IDE", description: "Small and lightweight IDE with basic features.", website: "https://www.geany.org", license: "GPL-2.0", platforms: ["windows", "macos", "linux"], tags: ["ide", "lightweight", "gtk"], alternatives_to: [], last_update: "2025-11-20", repo_url: "https://github.com/geany/geany", is_foss: true, stars: 3000, maturity: "stable" },
    { id: "lite-xl", category: "development", name: "Lite XL", tagline: "Lightweight editor", description: "Lightweight text editor written in Lua.", website: "https://lite-xl.com", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["editor", "lightweight", "lua"], alternatives_to: ["Sublime Text"], last_update: "2025-12-15", repo_url: "https://github.com/lite-xl/lite-xl", is_foss: true, stars: 4800, maturity: "stable" },
    { id: "micro", category: "development", name: "micro", tagline: "Terminal editor", description: "Modern and intuitive terminal-based text editor.", website: "https://micro-editor.github.io", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["editor", "terminal", "modern"], alternatives_to: ["nano", "vim"], last_update: "2025-12-20", repo_url: "https://github.com/zyedidia/micro", is_foss: true, stars: 25000, maturity: "stable" },
    { id: "kakoune", category: "development", name: "Kakoune", tagline: "Modal editor", description: "Modal editor with multiple selections and orthogonal design.", website: "https://kakoune.org", license: "Unlicense", platforms: ["linux", "macos"], tags: ["editor", "modal", "vim-like"], alternatives_to: ["Vim", "Neovim"], last_update: "2025-11-20", repo_url: "https://github.com/mawww/kakoune", is_foss: true, stars: 10000, maturity: "stable" },
    { id: "emacs", category: "development", name: "GNU Emacs", tagline: "Extensible editor", description: "Extensible, customizable, free text editor and more.", website: "https://www.gnu.org/software/emacs", license: "GPL-3.0", platforms: ["windows", "macos", "linux"], tags: ["editor", "lisp", "extensible"], alternatives_to: ["Vim"], last_update: "2025-12-20", repo_url: "https://github.com/emacs-mirror/emacs", is_foss: true, stars: 4500, maturity: "mature" },
    { id: "doom-emacs", category: "development", name: "Doom Emacs", tagline: "Emacs framework", description: "Emacs framework for the stubborn martian hacker.", website: "https://github.com/doomemacs/doomemacs", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["emacs", "framework", "vim-like"], alternatives_to: ["Spacemacs"], last_update: "2025-12-15", repo_url: "https://github.com/doomemacs/doomemacs", is_foss: true, stars: 19000, maturity: "stable" },
    { id: "spacemacs", category: "development", name: "Spacemacs", tagline: "Emacs distribution", description: "Community-driven Emacs distribution with Vim keybindings.", website: "https://www.spacemacs.org", license: "GPL-3.0", platforms: ["windows", "macos", "linux"], tags: ["emacs", "vim", "distribution"], alternatives_to: ["Doom Emacs"], last_update: "2025-11-20", repo_url: "https://github.com/syl20bnr/spacemacs", is_foss: true, stars: 23500, maturity: "stable" },

    // ==================== MORE DEVOPS ====================
    { id: "rancher", category: "devops", name: "Rancher", tagline: "Kubernetes management", description: "Complete container management platform for Kubernetes.", website: "https://rancher.com", license: "Apache-2.0", platforms: ["linux", "self-hosted"], tags: ["kubernetes", "management", "containers"], alternatives_to: ["OpenShift"], last_update: "2025-12-20", repo_url: "https://github.com/rancher/rancher", is_foss: true, stars: 23000, maturity: "stable" },
    { id: "lens", category: "devops", name: "Lens", tagline: "Kubernetes IDE", description: "The way the world runs Kubernetes.", website: "https://k8slens.dev", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["kubernetes", "ide", "management"], alternatives_to: [], last_update: "2025-12-15", repo_url: "https://github.com/lensapp/lens", is_foss: true, stars: 22500, maturity: "stable" },
    { id: "k9s", category: "devops", name: "K9s", tagline: "Kubernetes CLI", description: "Kubernetes CLI to manage your clusters in style.", website: "https://k9scli.io", license: "Apache-2.0", platforms: ["windows", "macos", "linux"], tags: ["kubernetes", "cli", "terminal"], alternatives_to: ["kubectl"], last_update: "2025-12-20", repo_url: "https://github.com/derailed/k9s", is_foss: true, stars: 27000, maturity: "stable" },
    { id: "kubectx", category: "devops", name: "kubectx", tagline: "Kubernetes context switcher", description: "Faster way to switch between clusters and namespaces.", website: "https://github.com/ahmetb/kubectx", license: "Apache-2.0", platforms: ["windows", "macos", "linux"], tags: ["kubernetes", "cli", "productivity"], alternatives_to: [], last_update: "2025-11-20", repo_url: "https://github.com/ahmetb/kubectx", is_foss: true, stars: 17500, maturity: "stable" },
    { id: "skaffold", category: "devops", name: "Skaffold", tagline: "Kubernetes development", description: "Easy and repeatable Kubernetes development.", website: "https://skaffold.dev", license: "Apache-2.0", platforms: ["windows", "macos", "linux"], tags: ["kubernetes", "development", "ci-cd"], alternatives_to: [], last_update: "2025-12-15", repo_url: "https://github.com/GoogleContainerTools/skaffold", is_foss: true, stars: 15000, maturity: "stable" },
    { id: "tilt", category: "devops", name: "Tilt", tagline: "Kubernetes dev environment", description: "Define your dev environment as code for Kubernetes.", website: "https://tilt.dev", license: "Apache-2.0", platforms: ["windows", "macos", "linux"], tags: ["kubernetes", "development", "local"], alternatives_to: ["Skaffold"], last_update: "2025-12-20", repo_url: "https://github.com/tilt-dev/tilt", is_foss: true, stars: 7500, maturity: "stable" },
    { id: "telepresence", category: "devops", name: "Telepresence", tagline: "Local K8s development", description: "Local development against a remote Kubernetes cluster.", website: "https://www.telepresence.io", license: "Apache-2.0", platforms: ["windows", "macos", "linux"], tags: ["kubernetes", "development", "remote"], alternatives_to: [], last_update: "2025-12-15", repo_url: "https://github.com/telepresenceio/telepresence", is_foss: true, stars: 6500, maturity: "stable" },
    { id: "pulumi", category: "devops", name: "Pulumi", tagline: "Infrastructure as Code", description: "Infrastructure as Code in any programming language.", website: "https://www.pulumi.com", license: "Apache-2.0", platforms: ["windows", "macos", "linux"], tags: ["iac", "cloud", "programming"], alternatives_to: ["Terraform"], last_update: "2025-12-20", repo_url: "https://github.com/pulumi/pulumi", is_foss: true, stars: 21500, maturity: "stable" },
    { id: "crossplane", category: "devops", name: "Crossplane", tagline: "Cloud infrastructure", description: "Build control planes without needing to write code.", website: "https://crossplane.io", license: "Apache-2.0", platforms: ["linux"], tags: ["kubernetes", "infrastructure", "cloud"], alternatives_to: ["Terraform"], last_update: "2025-12-15", repo_url: "https://github.com/crossplane/crossplane", is_foss: true, stars: 9500, maturity: "stable" },
    { id: "vault", category: "devops", name: "HashiCorp Vault", tagline: "Secrets management", description: "Secure, store and tightly control access to secrets.", website: "https://www.vaultproject.io", license: "BUSL-1.1", platforms: ["windows", "macos", "linux"], tags: ["secrets", "security", "encryption"], alternatives_to: [], last_update: "2025-12-20", repo_url: "https://github.com/hashicorp/vault", is_foss: true, stars: 31000, maturity: "mature" },
    { id: "consul", category: "devops", name: "HashiCorp Consul", tagline: "Service mesh", description: "Service networking solution to connect and secure services.", website: "https://www.consul.io", license: "BUSL-1.1", platforms: ["windows", "macos", "linux"], tags: ["service-mesh", "networking", "discovery"], alternatives_to: ["Istio"], last_update: "2025-12-15", repo_url: "https://github.com/hashicorp/consul", is_foss: true, stars: 28500, maturity: "mature" },
    { id: "nomad", category: "devops", name: "HashiCorp Nomad", tagline: "Workload orchestrator", description: "Simple and flexible workload orchestrator.", website: "https://www.nomadproject.io", license: "BUSL-1.1", platforms: ["windows", "macos", "linux"], tags: ["orchestration", "scheduling", "containers"], alternatives_to: ["Kubernetes"], last_update: "2025-12-20", repo_url: "https://github.com/hashicorp/nomad", is_foss: true, stars: 15000, maturity: "stable" },

    // ==================== MORE DATABASE TOOLS ====================
    { id: "redis", category: "database", name: "Redis", tagline: "In-memory data store", description: "Open-source, in-memory data structure store.", website: "https://redis.io", license: "BSD-3-Clause", platforms: ["linux", "macos", "windows"], tags: ["cache", "database", "in-memory"], alternatives_to: ["Memcached"], last_update: "2025-12-20", repo_url: "https://github.com/redis/redis", is_foss: true, stars: 66000, maturity: "mature" },
    { id: "valkey", category: "database", name: "Valkey", tagline: "Redis fork", description: "Open-source, high-performance key/value datastore.", website: "https://valkey.io", license: "BSD-3-Clause", platforms: ["linux", "macos"], tags: ["cache", "database", "redis-fork"], alternatives_to: ["Redis"], last_update: "2025-12-15", repo_url: "https://github.com/valkey-io/valkey", is_foss: true, stars: 16000, maturity: "growing" },
    { id: "mongodb", category: "database", name: "MongoDB", tagline: "Document database", description: "General purpose, document-based, distributed database.", website: "https://www.mongodb.com", license: "SSPL", platforms: ["windows", "macos", "linux"], tags: ["nosql", "document", "database"], alternatives_to: [], last_update: "2025-12-20", repo_url: "https://github.com/mongodb/mongo", is_foss: true, stars: 26000, maturity: "mature" },
    { id: "postgresql", category: "database", name: "PostgreSQL", tagline: "Relational database", description: "World's most advanced open-source relational database.", website: "https://www.postgresql.org", license: "PostgreSQL", platforms: ["windows", "macos", "linux"], tags: ["sql", "relational", "database"], alternatives_to: ["MySQL", "Oracle"], last_update: "2025-12-15", repo_url: "https://github.com/postgres/postgres", is_foss: true, stars: 16000, maturity: "mature" },
    { id: "mariadb", category: "database", name: "MariaDB", tagline: "MySQL fork", description: "Community-developed fork of MySQL.", website: "https://mariadb.org", license: "GPL-2.0", platforms: ["windows", "macos", "linux"], tags: ["sql", "mysql", "database"], alternatives_to: ["MySQL"], last_update: "2025-12-20", repo_url: "https://github.com/MariaDB/server", is_foss: true, stars: 5500, maturity: "mature" },
    { id: "cockroachdb", category: "database", name: "CockroachDB", tagline: "Distributed SQL", description: "Cloud-native distributed SQL database.", website: "https://www.cockroachlabs.com", license: "BSL-1.1", platforms: ["windows", "macos", "linux"], tags: ["sql", "distributed", "cloud-native"], alternatives_to: ["PostgreSQL"], last_update: "2025-12-15", repo_url: "https://github.com/cockroachdb/cockroach", is_foss: true, stars: 30000, maturity: "stable" },
    { id: "tidb", category: "database", name: "TiDB", tagline: "Distributed SQL", description: "Open-source, cloud-native, distributed SQL database.", website: "https://pingcap.com/tidb", license: "Apache-2.0", platforms: ["linux"], tags: ["sql", "distributed", "mysql-compatible"], alternatives_to: ["MySQL"], last_update: "2025-12-20", repo_url: "https://github.com/pingcap/tidb", is_foss: true, stars: 37000, maturity: "stable" },
    { id: "clickhouse", category: "database", name: "ClickHouse", tagline: "OLAP database", description: "Fast open-source column-oriented database management system.", website: "https://clickhouse.com", license: "Apache-2.0", platforms: ["linux", "macos"], tags: ["analytics", "olap", "columnar"], alternatives_to: ["Snowflake"], last_update: "2025-12-15", repo_url: "https://github.com/ClickHouse/ClickHouse", is_foss: true, stars: 37000, maturity: "stable" },
    { id: "duckdb", category: "database", name: "DuckDB", tagline: "Analytical database", description: "In-process SQL OLAP database management system.", website: "https://duckdb.org", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["analytics", "embedded", "sql"], alternatives_to: ["SQLite"], last_update: "2025-12-20", repo_url: "https://github.com/duckdb/duckdb", is_foss: true, stars: 23000, maturity: "stable" },
    { id: "sqlite", category: "database", name: "SQLite", tagline: "Embedded database", description: "Self-contained, serverless, zero-configuration SQL database engine.", website: "https://www.sqlite.org", license: "Public Domain", platforms: ["windows", "macos", "linux"], tags: ["embedded", "sql", "serverless"], alternatives_to: [], last_update: "2025-12-15", repo_url: "https://github.com/sqlite/sqlite", is_foss: true, stars: 6500, maturity: "mature" },
    { id: "surrealdb", category: "database", name: "SurrealDB", tagline: "Multi-model database", description: "Scalable, distributed, collaborative, document-graph database.", website: "https://surrealdb.com", license: "BSL-1.1", platforms: ["windows", "macos", "linux"], tags: ["multi-model", "graph", "document"], alternatives_to: [], last_update: "2025-12-20", repo_url: "https://github.com/surrealdb/surrealdb", is_foss: true, stars: 27000, maturity: "growing" },
    { id: "neo4j", category: "database", name: "Neo4j", tagline: "Graph database", description: "Native graph database built for connected data.", website: "https://neo4j.com", license: "GPL-3.0", platforms: ["windows", "macos", "linux"], tags: ["graph", "database", "cypher"], alternatives_to: [], last_update: "2025-12-15", repo_url: "https://github.com/neo4j/neo4j", is_foss: true, stars: 13000, maturity: "mature" },
    { id: "meilisearch", category: "database", name: "Meilisearch", tagline: "Search engine", description: "Lightning-fast search engine that fits effortlessly into your apps.", website: "https://www.meilisearch.com", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["search", "full-text", "fast"], alternatives_to: ["Elasticsearch", "Algolia"], last_update: "2025-12-20", repo_url: "https://github.com/meilisearch/meilisearch", is_foss: true, stars: 47000, maturity: "stable" },
    { id: "typesense", category: "database", name: "Typesense", tagline: "Search engine", description: "Fast, typo-tolerant search engine for building delightful search experiences.", website: "https://typesense.org", license: "GPL-3.0", platforms: ["windows", "macos", "linux"], tags: ["search", "typo-tolerant", "fast"], alternatives_to: ["Algolia", "Elasticsearch"], last_update: "2025-12-15", repo_url: "https://github.com/typesense/typesense", is_foss: true, stars: 20000, maturity: "stable" },
    { id: "elasticsearch", category: "database", name: "Elasticsearch", tagline: "Search & analytics", description: "Distributed, RESTful search and analytics engine.", website: "https://www.elastic.co/elasticsearch", license: "SSPL", platforms: ["windows", "macos", "linux"], tags: ["search", "analytics", "distributed"], alternatives_to: ["OpenSearch"], last_update: "2025-12-20", repo_url: "https://github.com/elastic/elasticsearch", is_foss: true, stars: 70000, maturity: "mature" },
    { id: "opensearch", category: "database", name: "OpenSearch", tagline: "Search & analytics", description: "Community-driven, open-source search and analytics suite.", website: "https://opensearch.org", license: "Apache-2.0", platforms: ["windows", "macos", "linux"], tags: ["search", "analytics", "elasticsearch-fork"], alternatives_to: ["Elasticsearch"], last_update: "2025-12-15", repo_url: "https://github.com/opensearch-project/OpenSearch", is_foss: true, stars: 9500, maturity: "stable" },

    // ==================== MORE WEB FRAMEWORKS ====================
    { id: "django", category: "web", name: "Django", tagline: "Python web framework", description: "High-level Python web framework for rapid development.", website: "https://www.djangoproject.com", license: "BSD-3-Clause", platforms: ["windows", "macos", "linux"], tags: ["python", "web", "batteries-included"], alternatives_to: ["Flask", "FastAPI"], last_update: "2025-12-20", repo_url: "https://github.com/django/django", is_foss: true, stars: 80000, maturity: "mature" },
    { id: "fastapi", category: "web", name: "FastAPI", tagline: "Modern Python API", description: "Modern, fast web framework for building APIs with Python.", website: "https://fastapi.tiangolo.com", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["python", "api", "async"], alternatives_to: ["Flask", "Django"], last_update: "2025-12-15", repo_url: "https://github.com/tiangolo/fastapi", is_foss: true, stars: 77000, maturity: "stable" },
    { id: "flask", category: "web", name: "Flask", tagline: "Python microframework", description: "Lightweight WSGI web application framework.", website: "https://flask.palletsprojects.com", license: "BSD-3-Clause", platforms: ["windows", "macos", "linux"], tags: ["python", "web", "microframework"], alternatives_to: ["Django"], last_update: "2025-12-20", repo_url: "https://github.com/pallets/flask", is_foss: true, stars: 68000, maturity: "mature" },
    { id: "rails", category: "web", name: "Ruby on Rails", tagline: "Ruby web framework", description: "Web application framework written in Ruby.", website: "https://rubyonrails.org", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["ruby", "web", "mvc"], alternatives_to: ["Django"], last_update: "2025-12-15", repo_url: "https://github.com/rails/rails", is_foss: true, stars: 56000, maturity: "mature" },
    { id: "laravel", category: "web", name: "Laravel", tagline: "PHP web framework", description: "PHP framework for web artisans.", website: "https://laravel.com", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["php", "web", "elegant"], alternatives_to: ["Symfony"], last_update: "2025-12-20", repo_url: "https://github.com/laravel/laravel", is_foss: true, stars: 78000, maturity: "mature" },
    { id: "symfony", category: "web", name: "Symfony", tagline: "PHP framework", description: "Set of reusable PHP components and a web application framework.", website: "https://symfony.com", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["php", "web", "components"], alternatives_to: ["Laravel"], last_update: "2025-12-15", repo_url: "https://github.com/symfony/symfony", is_foss: true, stars: 29500, maturity: "mature" },
    { id: "spring-boot", category: "web", name: "Spring Boot", tagline: "Java framework", description: "Makes it easy to create stand-alone, production-grade Spring applications.", website: "https://spring.io/projects/spring-boot", license: "Apache-2.0", platforms: ["windows", "macos", "linux"], tags: ["java", "web", "enterprise"], alternatives_to: [], last_update: "2025-12-20", repo_url: "https://github.com/spring-projects/spring-boot", is_foss: true, stars: 75000, maturity: "mature" },
    { id: "express", category: "web", name: "Express", tagline: "Node.js framework", description: "Fast, unopinionated, minimalist web framework for Node.js.", website: "https://expressjs.com", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["node", "web", "minimal"], alternatives_to: ["Fastify"], last_update: "2025-12-15", repo_url: "https://github.com/expressjs/express", is_foss: true, stars: 65000, maturity: "mature" },
    { id: "fastify", category: "web", name: "Fastify", tagline: "Fast Node.js framework", description: "Fast and low overhead web framework for Node.js.", website: "https://fastify.dev", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["node", "web", "fast"], alternatives_to: ["Express"], last_update: "2025-12-20", repo_url: "https://github.com/fastify/fastify", is_foss: true, stars: 32000, maturity: "stable" },
    { id: "nestjs", category: "web", name: "NestJS", tagline: "Node.js framework", description: "Progressive Node.js framework for building efficient server-side applications.", website: "https://nestjs.com", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["node", "typescript", "enterprise"], alternatives_to: ["Express"], last_update: "2025-12-15", repo_url: "https://github.com/nestjs/nest", is_foss: true, stars: 67000, maturity: "stable" },
    { id: "hono", category: "web", name: "Hono", tagline: "Ultrafast web framework", description: "Ultrafast web framework for the Edges.", website: "https://hono.dev", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["edge", "web", "ultrafast"], alternatives_to: ["Express"], last_update: "2025-12-20", repo_url: "https://github.com/honojs/hono", is_foss: true, stars: 20000, maturity: "growing" },
    { id: "gin", category: "web", name: "Gin", tagline: "Go web framework", description: "HTTP web framework written in Go.", website: "https://gin-gonic.com", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["go", "web", "fast"], alternatives_to: [], last_update: "2025-12-15", repo_url: "https://github.com/gin-gonic/gin", is_foss: true, stars: 79000, maturity: "stable" },
    { id: "fiber", category: "web", name: "Fiber", tagline: "Go web framework", description: "Express-inspired web framework built on top of Fasthttp.", website: "https://gofiber.io", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["go", "web", "express-like"], alternatives_to: ["Gin"], last_update: "2025-12-20", repo_url: "https://github.com/gofiber/fiber", is_foss: true, stars: 34000, maturity: "stable" },
    { id: "echo", category: "web", name: "Echo", tagline: "Go web framework", description: "High performance, extensible, minimalist Go web framework.", website: "https://echo.labstack.com", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["go", "web", "minimal"], alternatives_to: ["Gin"], last_update: "2025-12-15", repo_url: "https://github.com/labstack/echo", is_foss: true, stars: 30000, maturity: "stable" },
    { id: "actix-web", category: "web", name: "Actix Web", tagline: "Rust web framework", description: "Powerful, pragmatic, and extremely fast web framework for Rust.", website: "https://actix.rs", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["rust", "web", "fast"], alternatives_to: [], last_update: "2025-12-20", repo_url: "https://github.com/actix/actix-web", is_foss: true, stars: 22000, maturity: "stable" },
    { id: "axum", category: "web", name: "Axum", tagline: "Rust web framework", description: "Ergonomic and modular web framework built with Tokio.", website: "https://github.com/tokio-rs/axum", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["rust", "web", "tokio"], alternatives_to: ["Actix Web"], last_update: "2025-12-15", repo_url: "https://github.com/tokio-rs/axum", is_foss: true, stars: 19000, maturity: "stable" },
    { id: "phoenix", category: "web", name: "Phoenix", tagline: "Elixir web framework", description: "Web framework for Elixir that makes building APIs and web apps easy.", website: "https://www.phoenixframework.org", license: "MIT", platforms: ["windows", "macos", "linux"], tags: ["elixir", "web", "realtime"], alternatives_to: [], last_update: "2025-12-20", repo_url: "https://github.com/phoenixframework/phoenix", is_foss: true, stars: 21500, maturity: "stable" },
];

module.exports = { ultimateTools };
